/*M
.SH NAME
getmapnf - get matrix of polynomials over number field (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

matrix getmapnf(r,F,V,Vnf)
single r;
pol F;
list V,Vnf;

.SH DESCRIPTION
getmapnf() is equivalent to fgetmapnf() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetmapnf
M*/









/*H
	Version 1       02.01.1991      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getmapnf      : 910915.941201
H*/
/*
	For the definition of getmapnf please refer to the header file _matr3.h.
*/


