/*M
.SH NAME
getvecpnf - get vector of polynomials over number field (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

vec getvecpnf(r,F,VL,VLnf)
single r;
pol F;
list VL,VLnf;

.SH DESCRIPTION
getvecpnf() is equivalent to fgetvecpnf() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecpnf
M*/









/*H
	Version 1       02.01.1991      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecpnf     : 910915.941201
H*/
/*
	For the definition of getvecpnf please refer to the header file _matr3.h.
*/


