/*M
.SH NAME
isvecrfr - is vector of rational functions over the rational numbers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

single isvecrfr(r,V)
obj r,V;

.SH DESCRIPTION
isvecrfr() returns 1 if V is a vector of rational functions in r variables over the rational numbers
and 0 otherwise.
M*/






/*H
	Version 1       13.06.1989      U. Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isvecrfr      : 890801.9109__.941201
H*/
/*
	For the definition of isvecrfr please refer to the header file _matr3.h.
*/


