/*M
.SH NAME
marfrprod - matrix of rational functions over the rational numbers, product (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

matrix marfrprod(r, M, N)
single r;
matrix M,N;

.SH DESCRIPTION
marfrprod() returns the matrix M*N.

.PP
.TP 4
.B M,N
are matrices of rational functions in r variables over the rational numbers.
M and N must have compatible dimensions.
M*/








/*H
	Version 1       01.06.1989      U. Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE marfrprod     : 890801.9109__.941201
H*/
/*
	For the definition of marfrprod please refer to the header file _matr3.h.
*/


