/*M
.SH NAME
marfrcons1 - matrix of rational functions over the rational numbers, construction 1 (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

matrix marfrcons1(r, n)
single r,n;

.SH DESCRIPTION
marfrcons1() returns the n-dimensional unity matrix of
rational functions in r variables over the rational numbers.
M*/




/*H
	Version 1       05.06.1989      U. Schneiders, Th. Weis
	Version 2	05.07.1991	Th. Weis:
					list2( ... ) --> rtorfr( ... )
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE marfrcons1    : 890801.910915.941201
H*/
/*
	For the definition of marfrcons1 please refer to the header file _matr3.h.
*/


