/*M
.SH NAME
marfrvecmul - matrix of rational functions over the rational numbers vector, multiplication (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

vec marfrvecmul(r, A, x)
single r;
matrix A;
vec x;

.SH DESCRIPTION
marfrvecmul() returns the vector A*x.

.PP
.TP 4
.B A
is a matrix of rational functions in r variables over the rational numbers.
.TP 4
.B x
is a vector of rational functions in r variables over the rational numbers.

M*/






/*H
	Version 1       05.06.1989      U. Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE marfrvecmul   : 890801.9109__.941201
H*/
/*
	For the definition of marfrvecmul please refer to the header file _matr3.h.
*/


