/*M
.SH NAME
marfmsp1neg - matrix of rational functions over modular single primes, transcendence degree 1, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

matrix marfmsp1neg(p, M)
single p;
matrix M;

.SH DESCRIPTION
marfmsp1neg() returns the matrix -M.

.PP
.TP 4
.B p
must be prime.
.TP 4
.B M
is a matrix of rational functions in one variable over Z/pZ.
M*/






/*H
	Version 1       01.06.1989      U. Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE marfmsp1neg   : 890801.9109__.941201
H*/
/*
	For the definition of marfmsp1neg please refer to the header file _matr3.h.
*/


