/*M
.SH NAME
putmapgf2 - put matrix of polynomials over Galois-field of characteristic 2  (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

single putmapgf2(r, M, G, VL, Vgf2)
single r;
matrix M;
obj G;
list VL, Vgf2;

.SH DESCRIPTION
putmapgf2() is equivalent to fputmapgf2() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmapgf2
M*/
/*H
	Version 1	22.06.1995	E.Herrmann
   DATE putmapgf2     : 951201
H*/
/*
	For the definition of putmapgf2 please refer to the header file _matr3.h
*/


