/*M
.SH NAME
putmapgfs - put matrix of polynomials over Galois-field with single  characteristic (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

single putmapgfs(r,p,AL,M,V,Vgfs)
single r,p;
list AL;
matrix M;
list V,Vgfs;

.SH DESCRIPTION
putmapgfs() is equivalent to fputmapgfs() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmapgfs
M*/









/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmapgfs     : 910915.941201
H*/
/*
	For the definition of putmapgfs please refer to the header file _matr3.h.
*/


