/*M
.SH NAME
putmapnf - put matrix of polynomials over number field (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

single putmapnf(r,F,M,V,Vnf)
single r;
pol F;
matrix M;
list V,Vnf;

.SH DESCRIPTION
putmapnf() is equivalent to fputmapnf() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmapnf
M*/









/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmapnf      : 910915.941201
H*/
/*
	For the definition of putmapnf please refer to the header file _matr3.h.
*/


