/*M
.SH NAME
putvecpnf - put vector of polynomials over number field (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

single putvecpnf(r,F,W,VL,VLnf)
single r;
pol F;
vec W;
list VL,VLnf;

.SH DESCRIPTION
putvecpnf() is equivalent to fputvecpnf() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecpnf
M*/









/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecpnf     : 910915.941201
H*/
/*
	For the definition of putvecpnf please refer to the header file _matr3.h.
*/


