/*M
.SH NAME
putvpgfs - put vector of polynomials over Galois-field with single  characteristic (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

single putvpgfs(r,p,AL,W,V,Vgfs)
single r,p;
list AL;
vec W;
list V,Vgfs;

.SH DESCRIPTION
putvpgfs() is equivalent to fputvpgfs() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvpgfs
M*/









/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvpgfs      : 910915.941201
H*/
/*
	For the definition of putvpgfs please refer to the header file _matr3.h.
*/


