/*M
.SH NAME
putvecrfr - put vector of rational functions over the rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

single putvecrfr(r,V,VL)
single r;
vec V;
list VL;

.SH DESCRIPTION
putvecrfr() is equivalent to fputvecrfr() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecrfr
M*/









/*H
	Version 1       13.06.1989      U.Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecrfr     : 890801.9109__.941201
H*/
/*
	For the definition of putvecrfr please refer to the header file _matr3.h.
*/


