/*M
.SH NAME
vecrfmsp1neg - vector of rational functions over modular single primes, transcendence degree 1, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

vec vecrfmsp1neg(p, V)
single p;
vec V;

.SH DESCRIPTION
vecrfmsp1neg() returns the vector -V.

.PP
.TP 4
.B p
must be prime.
.TP 4
.B V
is a vector of rational functions in one variable over Z/pZ.
M*/








/*H
	Version 1       14.06.1989      U.Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecrfmsp1neg  : 890801.9109__.941201
H*/
/*
	For the definition of vecrfmsp1neg please refer to the header file _matr3.h.
*/


