/*M
.SH NAME
vecrfrsum - vector of rational functions over the rational numbers sum (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

vec vecrfrsum(r,U,V)
single r;
vec U,V;

.SH DESCRIPTION
vecrfrsum() returns the vector U+V.
.PP
.TP 4
.B U,V
are vectors of rational functions in r variables over the rational numbers.
U and V must have equal length.
M*/









/*H
	Version 1       14.06.1989      U.Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecrfrsum     : 890801.9109__.941201
H*/
/*
	For the definition of vecrfrsum please refer to the header file _matr3.h.
*/


