/*M
.SH NAME
vecrfmsp1sum - vector of rational functions over modular single primes,  transcendence degree 1, sum (MACRO)

.SH SYNOPSIS
.nf
#include<_matr3.h>

vec vecrfmsp1sum(p, U, V)
single p;
vec U,V;

.SH DESCRIPTION
vecrfmsp1sum() returns the vector U+V.
.PP
.TP 4
.B p
must be prime.
.TP 4
.B U,V
are vectors of rational functions in one variable over Z/pZ.
U and V must have equal length.
M*/









/*H
	Version 1       14.06.1989      U.Schneiders, Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecrfmsp1sum  : 890801.9109__.941201
H*/
/*
	For the definition of vecrfmsp1sum please refer to the header file _matr3.h.
*/


