/*M
.SH NAME
creal - complex real part (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

floating creal(z)
complex z;

.SH DESCRIPTION
creal() returns the real part of the complex number z.
M*/

/*H
        Version 1	16.01.1993  	Georg Lay
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE creal         : 930531.941201
H*/
/*
	For the definition of creal please refer to the header file _arith1.h.
*/
