/*M
.SH NAME
flsign - floating point sign (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single flsign(f)
floating f;

.SH DESCRIPTION
flsign() returns the sign of f.
M*/
/*H
	Version  1      21.03.1991      Marc Conrad
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE flsign        : 910715.941201
H*/
/*
	For the definition of flsign please refer to the header file _arith1.h.
*/
