/*M
.SH NAME
getli - get list of integers (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

list getli(pf);

.SH DESCRIPTION
getli() returns a list of integers read in from stdin,
or ERROR in case an error occurs.
M*/
/*H
	Version  1      22.04.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getli         : 890501.941201
H*/
/*
	For the definition of getli please refer to the header file _arith1.h.
*/
