/*M
.SH NAME
getms - get modular single (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single getms(m)
single m;

.SH DESCRIPTION
For m >0
getms() returns the integer read in from stdin reduced modulo m,
or ERROR in case an error occurs.
M*/

/*H
	Version 1       8.4.1987                Pascale Serf
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getms         : 890501.941201
H*/
/*
	For the definition of getms please refer to the header file _arith1.h.
*/
