/*M
.SH NAME
getr - get rational number (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

rat getr();

.SH DESCRIPTION
getr() returns the reduced rational value read from stdin,
or ERROR in case an error occurs.
M*/

/*H
	Version  1      16.03.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getr          : 890501.941201
H*/
/*
	For the definition of getr please refer to the header file _arith1.h.
*/
