/*M
.SH NAME
getsi - get single precision (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single getsi();

.SH DESCRIPTION
getsi() returns the single integer value read from stdin,
or ERROR in case an error occurs.
M*/

/*H
	Version  1      16.03.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getsi         : 890501.941201
H*/
/*
	For the definition of getsi please refer to the header file _arith1.h.
*/
