/*M
.SH NAME
iabs - integer absolute value (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

int iabs(A)
int A;

.SH DESCRIPTION
iabs() returns the absolute value |A| of A.
M*/
/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE iabs          : 890501.941201
H*/
/*
	For the definition of iabs please refer to the header file _arith1.h.
*/
