/*M
.SH NAME
imin - integer minimum (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

int imin(A,B)
int A,B;

.SH DESCRIPTION
imin() returns the minimum of A and B.
M*/
/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE imin          : 890501.941201
H*/
/*
	For the definition of imin please refer to the header file _arith1.h.
*/
