/*M
.SH NAME
iquot - integer quotient (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

int iquot(A, B)
int A, B;

.SH DESCRIPTION
iquot() returns the integer part of A / B.
M*/
/*H
			
	Version 1       28.07.1986      R.Boeffgen
	Version 2	18.11.1994	Macro nur noch im Header definiert.
					Neuer Dokumentationsstandard. MP
   DATE iquot         : 890501.941201
H*/
/*
	For the definition of iquot please refer to the header file _arith1.h.
*/
