/*M
.SH NAME
isquot - integer single-precision quotient (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

int isquot(A,b)
int A;
single b;

.SH DESCRIPTION
isquot() returns the integer part of a / b for b!=0.
M*/
/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isquot        : 890501.941201
H*/
/*
	For the definition of isquot please refer to the header file _arith1.h.
*/
