/*M
.SH NAME
itrunc - integer truncation (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

int itrunc(A,n)
int A;
single n;

.SH DESCRIPTION
itrunc() returns the integer part of A / 2^n .
M*/
/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE itrunc        : 890501.941201
H*/
/*
	For the definition of itrunc please refer to the header file _arith1.h.
*/
