/*M
.SH NAME
m4hom - modular 4 homomorphism (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single m4hom(a)
int a;

.SH DESCRIPTION
m4hom() returns the representative of a (mod 4)
in the residue system {0, 1, 2, 3}.
M*/      
/*H
	Version 1       14.10.1993      Josef Gebel
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE m4hom         : 931130.941201
H*/
/*
	For the definition of m4hom please refer to the header file _arith1.h.
*/
