/*M
.SH NAME
mineg - modular integer negation (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

int mineg(M,A)
int M,A;

.SH DESCRIPTION
mineg() returns -A for M > 0 and A from Z/MZ.
M*/
/*H
	Version 1        9.2.1987               Pascale Serf
	Version 2       12.3.1987               Laufzeit jetzt kuerzer
						  Pascale Serf
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE mineg         : 890501.941201
H*/
/*
	For the definition of mineg please refer to the header file _arith1.h.
*/
