/*M
.SH NAME
msdif - modular single difference (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single msdif(m,a,b)
single m,a,b;

.SH DESCRIPTION
msdif() returns a - b for m > 0 and a,b from Z/mZ.
M*/
/*H
	Version 1       28.11.1986      B. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE msdif         : 890501.941201
H*/
/*
	For the definition of msdif please refer to the header file _arith1.h.
*/
