/*M
.SH NAME
mshoms - modular single-precision homomorphism, symmetric residue system (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single mshoms(m,A)
single m;
int A;

.SH DESCRIPTION
mshoms() returns the representative of A
in the symmetric residue system Z/MZ for M>0.
M*/

/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE mshoms        : 890501.941201
H*/
/*
	For the definition of mshoms please refer to the header file _arith1.h.
*/
