/*M
.SH NAME
msneg - modular single negation (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single msneg(m,a)
single m,a;

.SH DESCRIPTION
msneg() returns -a for m > 0 and a from Z/mZ.
M*/
/*H
	Version 1       28.11.1986      B. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE msneg         : 890501.941201
H*/
/*
	For the definition of msneg please refer to the header file _arith1.h.
*/
