/*M
.SH NAME
msquot - modular single quotient (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single msquot(m,a,b)
single m,a,b;

.SH DESCRIPTION
msquot() returns a / b for m > 0, a from Z/mZ and b from (Z/mZ)*.
M*/

/*H
	Version 1        2.12.1986      B. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE msquot        : 890501.941201
H*/
/*
	For the definition of msquot please refer to the header file _arith1.h.
*/
