/*M
.SH NAME
putbi - put bits (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single putbi(N)
int N;


.SH DESCRIPTION
putbi() writes the bitwise notation of the integer N
to stdout and returns 0.
In case of a failure, the return code is ERROR.
M*/

/*H
	Version  1      16.02.1996      S.Schmitt
   DATE putbi	      : 960501
H*/
/*
	For the definition of putbi please refer to the header file _arith1.h.
*/
