/*M
.SH NAME
puti - put integer (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single puti(A)
int A;

.SH DESCRIPTION
puti() writes the integer A
to stdout and returns 0.
In case of a failure, the return code is ERROR.
M*/

/*H
	Version 1       04.03.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE puti          : 890501.941201
H*/
/*
	For the definition of puti please refer to the header file _arith1.h.
*/
