/*M
.SH NAME
putli - put list of integers (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single putli(L)
list L;

.SH DESCRIPTION
putli() writes the integer list L
to stdout and returns 0.
In case of a failure, the return code is ERROR.
M*/

/*H
	Version 1       04.03.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putli         : 890501.941201
H*/
/*
	For the definition of putli please refer to the header file _arith1.h.
*/
