/*M
.SH NAME
rabs - rational number absolute value (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

rat rabs(R)
rat R;

.SH DESCRIPTION
rabs() returns the absolute value |R| of R.
M*/
/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE rabs          : 890501.941201
H*/
/*
	For the definition of rabs please refer to the header file _arith1.h.
*/
