/*M
.SH NAME
rden - rational number denominator (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

int rden(R)
rat R;

.SH DESCRIPTION
rden() returns the  denominator or R.
M*/
/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE rden          : 890501.941201
H*/
/*
	For the definition of rden please refer to the header file _arith1.h.
*/
