/*M
.SH NAME
seven - single-precision even (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single seven(x)
single x;

.SH DESCRIPTION
seven() returns 1, if x is even and 0, if x is odd.
M*/
/*H
	Version 1       28.07.1986              R.Boeffgen
  	Version 2       22.08.1989              V. Schwinn !(n&1)
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE seven         : 890501.891101.941201
H*/
/*
	For the definition of seven please refer to the header file _arith1.h.
*/
