/*M
.SH NAME
smax - single-precision maximum (MACRO)

.SH SYNOPSIS
.nf
#include<_arith1.h>

single smax(a,b)
single a,b;

.SH DESCRIPTION
smax() returns the maximum of a and b.
M*/
/*H
	Version 1       28.7.1986               R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE smax          : 890501.941201
H*/
/*
	For the definition of smax please refer to the header file _arith1.h.
*/
