/*M
.SH NAME
geta - get atom (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

atom geta( ) 

.SH DESCRIPTION
geta reads an atom from stdin and returns it. In case of an error, geta returns ERROR.

M*/
          
/*H
	Version  1      24.02.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE geta          : 890501.941201
H*/
/*
	For the definition of geta please refer to the header file _list.h.
*/
