/*M
.SH NAME
getcb - get character, skipping blanks (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single getcb( ) 

.SH DESCRIPTION
getcb read a character from stdin and returns it. Blanks will be ignored. In case of an error or end of file, getcb returns EOF.

M*/
       
/*H
	Version  1      24.02.1987      R.Boeffgen
	Version  2      24.03.1987      Name geaendert.   RB
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE getcb         : 890501.941201
H*/
/*
	For the definition of getcb please refer to the header file _list.h.
*/
