/*M
.SH NAME
geto - get object (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

obj geto()

.SH DESCRIPTION
geto reads an object from stdin and returns it. In case of an error, geto returns ERROR.

M*/
     
/*H
	Version  1      04.03.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE geto          : 890501.941201
H*/
/*
	For the definition of geto please refer to the header file _list.h.
*/
