/*M
.SH NAME
isobj - is object ? (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single isobj(a)  
unsigned a;
   
.SH DESCRIPTION
isobj returns 
.TP 4
1,
if a is an object, i.e. an atom or a list, and
.TP 4
0,
else.

M*/
     
/*H
	Version 1       14.03.1988              Pascale Serf
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isobj         : 890501.941201
H*/
/*
	For the definition of isobj please refer to the header file _list.h.
*/
