/*M
.SH NAME
issingle - is single ?  (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single issingle(a)  
obj a;
  
.SH DESCRIPTION
issingle returns 
.TP 4
1, 
if a is a single, and
.TP 4
0,
else.

M*/
     
/*H
	Version 1       5.1.1987                Pascale Serf
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE issingle      : 890501.941201
H*/
/*
	For the definition of issingle please refer to the header file _list.h.
*/
