/*M
.SH NAME
lines - lines
(MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single lines(k)  
single k;

.SH DESCRIPTION
.TP 4
.B k
is an integer number, k < BASIS.
.PP
lines writes k linefeeds on stdout, and returns 0 by suc-cess, and ERROR else.


M*/
         
/*H
	Version 1       24.11.1986      R. Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE lines         : 890501.941201
H*/
/*
	For the definition of lines please refer to the header file _list.h.
*/
