/*M
.SH NAME
list4 - list of 4 objects (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

list list4(a_1, a_2, a_3, a_4)
obj a_1, a_2, a_3, a_4;

.SH DESCRIPTION
list4 returns the list (a_1, a_2, a_3, a_4).

M*/
         
/*H
	Version 1       14.10.1986
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE list4         : 890501.941201
H*/
/*
	For the definition of list4 please refer to the header file _list.h.
*/
