/*M
.SH NAME
list6 - list of 6 objects (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

list list6(a_1, a_2, a_3, a_4, a_5, a_6)
obj a_1, a_2, a_3, a_4, a_5, a_6;

.SH DESCRIPTION
list6 returns the list (a_1, a_2, a_3, a_4, a_5, a_6).

M*/
          
/*H
	Version 1       14.10.1986              R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE list6         : 890501.941201
H*/
/*
	For the definition of list6 please refer to the header file _list.h.
*/
