/*M
.SH NAME
list3 - list of 3 objects (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

list list3(a_1, a_2, a_3)
obj a_1, a_2, a_3;

.SH DESCRIPTION
list3 returns the list (a_1, a_2, a_3).

M*/
         
/*H
	Version 1       14.10.1986              R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE list3         : 890501.941201
H*/
/*
	For the definition of list3 please refer to the header file _list.h.
*/
