/*M
.SH NAME
list2 - list of 2 objects (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

list list2(a_1, a_2)
obj a_1, a_2;

.SH DESCRIPTION
list2 returns the list (a_1, a_2).

M*/
        
/*H
	Version 1       14.10.1986              R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE list2         : 890501.941201
H*/
/*
	For the definition of list2 please refer to the header file _list.h.
*/
