/*M
.SH NAME
list1 - list of one object (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

list list1(a)  
obj a;
 
.SH DESCRIPTION
list1 returns the list (a).

M*/
           
/*H
	Version 1       14.10.1986              R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE list1         : 890501.941201
H*/
/*
	For the definition of list1 please refer to the header file _list.h.
*/
