/*M
.SH NAME
lsize - list size (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single lsize (L)  
list L;
 
.SH DESCRIPTION
.TP 4
.B L
is a list.
.PP
lsize returns the number of ASCII-characters (incl. the terminating character) necessary to print L.

M*/
         
/*H
	Version 1	14.10.1992	Georg Lay
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE lsize         : 921130.941201
H*/
/*
	For the definition of lsize please refer to the header file _list.h.
*/
