/*M
.SH NAME
lthird - list third (MACRO)

.SH SYNOPSIS
.nf
#include<_ec3.h>

obj lthird(L)
list L;

.SH DESCRIPTION
lthird() returns the third object of the list L.
L must have at least 3 objects.
M*/

/*H
	Version 1       14.10.1986      R.Boeffgen
	Version 2       11.12.1989      einheitl. Version fuer MX2, MX2+, SUN
					und Apollo. PS
	Version 3	03.11.1994	MX-Version entfernt. MP
	Version 4	18.11.1994	Macro nur noch im Header definiert. MP
	Version 5	22.11.1994	Neuer Dokumentationsstandard. MP
   DATE lthird        : 890501.900101.941201
H*/
/*
	For the definition of lthird please refer to the header file _list.h.
*/
