/*M
.SH NAME
puta - put atom (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single puta(a)  
atom a;

.SH DESCRIPTION
puta writes the atom a to stdout and returns 0 by success and ERROR else.

M*/
          
/*H
	Version 1       24.02.1987      R.Boeffgen
	Version 2       24.03.1987      Fehlerausgabe ERROR.  RB
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE puta          : 890501.941201
H*/
/*
	For the definition of puta please refer to the header file _list.h.
*/
