/*M
.SH NAME
putbits - put bits (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single putbits(s)  
unsigned s;
  
.SH DESCRIPTION
putbits writes s bit by bit to stdout and returns 0 by success and ERROR else.

M*/
        
/*H
	Version 1       04.03.87        R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putbits       : 890501.941201
H*/
/*
	For the definition of putbits please refer to the header file _list.h.
*/
