/*M
.SH NAME
putchar - put character (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single putchar(c)  
char c; 

.SH DESCRIPTION
putchar writes the character c to stdout and returns c by success and EOF else.

M*/
         
/*H
	Version 1       18.03.1987      R. Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putchar       : 890501.941201
H*/
/*
	For the definition of putchar please refer to the header file _list.h.
*/
