/*M
.SH NAME
putl - put list (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

single putl(L)  
list L;
 
.SH DESCRIPTION
putl writes the list L to stdout and returns 0 by success and ERROR else.

M*/
         
/*H
	Version 1       04.03.1987      R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putl          : 890501.941201
H*/
/*
	For the definition of putl please refer to the header file _list.h.
*/
