/*M
.SH NAME
putstruct - put list structure (MACRO)
 
.SH SYNOPSIS
.nf
#include<_list.h>

single putlstruct(L)  
list L;
 
.SH DESCRIPTION
putlstruct writes the structure of the list L, i.e. the adresses and values of the several list cells, to stdout.

M*/
       
/*H
	Version 1       7.4.1987                Pascale Serf
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putlstruct    : 890501.941201
H*/
/*
	For the definition of putlstruct please refer to the header file _list.h.
*/
