/*M
.SH NAME
usunion - unordered set union (MACRO)

.SH SYNOPSIS
.nf
#include<_list.h>

list usunion(L1, L2)  
list L1, L2;
 
.SH DESCRIPTION
.TP 4
.B L1, L2
are lists.
.PP   
usunion returns a list, containing the union of L1 and L2.

M*/
         
/*H
	Version 1       14.10.1986              R.Boeffgen
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE usunion       : 890501.941201
H*/
/*
	For the definition of usunion please refer to the header file _list.h.
*/
