/*M
.SH NAME
fgetmai - file get matrix of integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix fgetmai(pf)
FILE *pf;

.SH DESCRIPTION
fgetmai() returns the matrix of integers
read from the input file *pf or ERROR in case an error has occurred.

.PP
.TP 4
.B pf
is a pointer to the input file.
M*/








/*H
	Version 1       04.05.1988      Klaus Petry
	Version 2       24.10.1988      Klaus Petry     Macro
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE fgetmai       : 890501.941201
H*/
/*
	For the definition of fgetmai please refer to the header file _matr1.h.
*/
