/*M
.SH NAME
fgetmar - file get matrix of rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix fgetmar(pf)
FILE *pf;

.SH DESCRIPTION
fgetmar() returns the matrix of rational numbers
read from the input file *pf or ERROR in case an error has occurred.

.PP
.TP 4
.B pf
is a pointer to the input file.

.SH SEE ALSO
fgetr
M*/









/*H
	Version 1       04.05.1988      Klaus Petry
	Version 2       02.11.1988      Klaus Petry     Macro
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE fgetmar       : 890501.941201
H*/
/*
	For the definition of fgetmar please refer to the header file _matr1.h.
*/
