/*M
.SH NAME
getmapms - get matrix of polynomials over modular singles (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix getmapms(r, m, V)
single r, m;
list V;

.SH DESCRIPTION
getmapms() is equivalent to fgetmapms() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetmapms
M*/




/*H
	Version  1      02.11.1988      KLaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getmapms      : 890501.9203__.941201
H*/
/*
	For the definition of getmapms please refer to the header file _matr1.h.
*/
