/*M
.SH NAME
getmar - get matrix of rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix getmar();

.SH DESCRIPTION
getmar() is equivalent to fgetmar() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetmar
M*/




/*H
	Version 1       04.05.1988      Klaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getmar        : 890501.941201
H*/
/*
	For the definition of getmar please refer to the header file _matr1.h.
*/
