/*M
.SH NAME
getmams - get matrix of modular singles (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix getmams(m)
single m;

.SH DESCRIPTION
getmams() is equivalent to fgetmams() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetmams
M*/




/*H
	Version  1      27.06.1988      KLaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getmams       : 890501.9203__.941201
H*/
/*
	For the definition of getmams please refer to the header file _matr1.h.
*/
