/*M
.SH NAME
getvecpi - get vector of polynomials over integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec getvecpi(r, VL)
single r;
list VL;

.SH DESCRIPTION
getvecpi() is equivalent to fgetvecpi() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecpi
M*/




/*H
	Version 1       27.02.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecpi      : 890601.941201
H*/
/*
	For the definition of getvecpi please refer to the header file _matr1.h.
*/
