/*M
.SH NAME
getvecmi - get vector of modular integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec getvecmi(m)
int m;

.SH DESCRIPTION
getvecmi() is equivalent to fgetvecmi() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecmi
M*/




/*H
	Version 1       31.01.1992      Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecmi      : 920331.941201
H*/
/*
	For the definition of getvecmi please refer to the header file _matr1.h.
*/
