/*M
.SH NAME
getvecr - get vector of rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec getvecr();

.SH DESCRIPTION
getvecr() is equivalent to fgetvecr() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecr
M*/




/*H
	Version 1       27.02.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecr       : 890601.941201
H*/
/*
	For the definition of getvecr please refer to the header file _matr1.h.
*/
