/*M
.SH NAME
getvecms - get vector of modular singles (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec getvecms(m)
single m;

.SH DESCRIPTION
getvecms() is equivalent to fgetvecms() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecms
M*/




/*H
	Version 1       27.02.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecms      : 890601.9203__.941201
H*/
/*
	For the definition of getvecms please refer to the header file _matr1.h.
*/
