/*M
.SH NAME
getvecpr - get vector of polynomials over the rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec getvecpr(r, VL)
single r;
list VL;

.SH DESCRIPTION
getvecpr() is equivalent to fgetvecpr() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecpr
M*/




/*H
	Version 1       27.02.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecpr      : 890601.941201
H*/
/*
	For the definition of getvecpr please refer to the header file _matr1.h.
*/
