/*M
.SH NAME
ismapmi - is matrix of polynomials over modular integers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single ismapmi(r, m, M)
obj r, m, M;

.SH DESCRIPTION
ismapmi() returns 1, if M is a matrix of polynomials in r variables over Z/mZ
and 0 otherwise.
M*/
/*H
	Version 1       31.01.1992      Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE ismapmi       : 920331.941201
H*/
/*
	For the definition of ismapmi please refer to the header file _matr1.h.
*/
