/*M
.SH NAME
ismadpr - is matrix of dense polynomials over the rational numbers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single ismadpr(r, M)
obj r, M;

.SH DESCRIPTION
ismadpr() returns 1, if M is a matrix of dense polynomials in r variables over the rational numbers
and 0 otherwise.
M*/






/*H
	Version 1       11.01.1991      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE ismadpr       : 910915.941201
H*/
/*
	For the definition of ismadpr please refer to the header file _matr1.h.
*/
