/*M
.SH NAME
ismadpi - is matrix of dense polynomials over integers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single ismadpi(r, M)
obj r, M;

.SH DESCRIPTION
ismadpi() returns 1, if M is a matrix of dense polynomials in r variables over integers
and 0 otherwise.
M*/
/*H
	Version 1       11.01.1991      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE ismadpi       : 910915.941201
H*/
/*
	For the definition of ismadpi please refer to the header file _matr1.h.
*/
