/*M
.SH NAME
ismadp - is matrix of dense polynomials ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single ismadp(r, M)
obj r, M;

.SH DESCRIPTION
ismadp() returns 1, if M is a matrix of dense polynomials in r variables
and 0 otherwise.
M*/
/*H
	Version 1       11.01.1991      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE ismadp        : 910915.941201
H*/
/*
	For the definition of ismadp please refer to the header file _matr1.h.
*/
