/*M
.SH NAME
ismai - is matrix of integers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single ismai(M)
obj M;

.SH DESCRIPTION
ismai() returns 1, if M is a matrix of integers
and 0 otherwise.
M*/
/*H
	Version 1       03.05.1988      Klaus Petry
	Version 2       22.11.1988      Klaus Petry     Macro
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE ismai         : 890501.941201
H*/
/*
	For the definition of ismai please refer to the header file _matr1.h.
*/
