/*M
.SH NAME
ismap - is matrix of polynomials ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single ismap(r, M)
obj r, M;

.SH DESCRIPTION
ismap() returns 1, if M is a matrix of polynomials in r variables
and 0 otherwise.
M*/
/*H
	Version 1       09.08.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE ismap         : 910915.941201
H*/
/*
	For the definition of ismap please refer to the header file _matr1.h.
*/
