/*M
.SH NAME
isnullma - is null-matrix (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single isnullma(M)
matrix M;

.SH DESCRIPTION
isnullma() returns returns 1, if all entries of the matrix M are zero
and 0 otherwise.
M*/
/*H
	Version 1       31.10.1988      Klaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isnullma      : 890501.9203__.941201
H*/
/*
	For the definition of isnullma please refer to the header file _matr1.h.
*/
