/*M
.SH NAME
isveci - is vector of integers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single isveci(V)
obj V;

.SH DESCRIPTION
isveci() returns 1, if V is a vector of integers
and 0 otherwise.
M*/




/*H
	Version 1       21.02.1989      Ursula Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isveci        : 890601.941201
H*/
/*
	For the definition of isveci please refer to the header file _matr1.h.
*/
