/*M
.SH NAME
isvecpi - is vector of polynomials over integers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single isvecpi(r, V)
obj r, V;

.SH DESCRIPTION
isvecpi()  returns 1, if V is a vector of polynomials in r variables over integers
and 0 otherwise.
M*/




/*H
	Version 1       27.02.1989      U. Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isvecpi       : 890601.941201
H*/
/*
	For the definition of isvecpi please refer to the header file _matr1.h.
*/
