/*M
.SH NAME
isvecr - is vector of rational numbers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single isvecr(V)
obj V;

.SH DESCRIPTION
isvecr() returns 1, if V is a vector of rational numbers
and 0 otherwise.
M*/




/*H
	Version 1       21.02.1989      Ursula Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isvecr        : 890601.941201
H*/
/*
	For the definition of isvecr please refer to the header file _matr1.h.
*/
