/*M
.SH NAME
isvecpms - is vector of polynomials over modular singles ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single isvecpms(r, m, V)
obj r, m, V;

.SH DESCRIPTION
isvecpms()  returns 1, if V is a vector of polynomials in r variables over Z/mZ
and 0 otherwise.
M*/




/*H
	Version 1       27.02.1989      U. Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isvecpms      : 890601.941201
H*/
/*
	For the definition of isvecpms please refer to the header file _matr1.h.
*/
