/*M
.SH NAME
isvecdpi - is vector of dense polynomials over integers ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single isvecdpi(r, V)
obj r, V;

.SH DESCRIPTION
isvecdpi() returns 1, if V is a vector of dense polynomials in r variables over integers
and 0 otherwise.
M*/




/*H
	Version 1       11.01.1991      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isvecdpi      : 910915.941201
H*/
/*
	For the definition of isvecdpi please refer to the header file _matr1.h.
*/
