/*M
.SH NAME
isvecms - is vector of modular singles ? (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single isvecms(m, V)
obj m, V;

.SH DESCRIPTION
isvecms() returns 1, if V is a vector over Z/mZ
and 0 otherwise.
M*/




/*H
	Version 1       15.12.1988      Pascale Serf
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE isvecms       : 890501.941201
H*/
/*
	For the definition of isvecms please refer to the header file _matr1.h.
*/
