/*M
.SH NAME
maicons1 - matrix of integers, construction 1 (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix maicons1(n)
single n;

.SH DESCRIPTION
maicons1() returns the n-dimensional unity matrix of
integers.

M*/
/*H
	Version 1       03.06.1988      Klaus Petry
	Version 2       09.02.1989      Klaus Petry     Macro
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE maicons1      : 890501.941201
H*/
/*
	For the definition of maicons1 please refer to the header file _matr1.h.
*/
