/*M
.SH NAME
maidif - matrix of integers, difference (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix maidif(M, N)
matrix M, N;

.SH DESCRIPTION
maidif() returns the matrix M-N.

.PP
.TP 4
.B M, N
are matrices of integers.
M and N must have equal dimensions.
M*/


/*H
	Version  1      07.06.1988      KLaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE maidif        : 890501.941201
H*/
/*
	For the definition of maidif please refer to the header file _matr1.h.
*/
