/*M
.SH NAME
maiprod - matrix of integers, product (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix maiprod(M, N)
matrix M, N;

.SH DESCRIPTION
maiprod() returns the matrix M*N.

.PP
.TP 4
.B M,N
are matrices of integers.
M and N must have compatible dimensions.
M*/
/*H
	Version 1       19.05.1988      Klaus Petry
	Version 2       14.11.1988      Klaus Petry
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE maiprod       : 890501.941201
H*/
/*
	For the definition of maiprod please refer to the header file _matr1.h.
*/
