/*M
.SH NAME
maisum - matrix of integers, sum (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix maisum(M, N)
matrix M, N;

.SH DESCRIPTION
maisum() returns the matrix M+N.

.PP
.TP 4
.B M, N
are matrices of integers.
M and N must have equal dimensions.
M*/
/*H
	Version 1       13.05.1988      Klaus Petry
	Version 2       10.11.1988      Klaus Petry
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE maisum        : 890501.941201
H*/
/*
	For the definition of maisum please refer to the header file _matr1.h.
*/
