/*M
.SH NAME
mamsneg - matrix of modular singles, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix mamsneg(m, M)
single m;
matrix M;

.SH DESCRIPTION
mamsneg() returns the matrix -M.

.PP
.TP 4
.B M
is a matrix over Z/mZ.
M*/
/*H
	Version 1       27.06.1988      Klaus Petry
	Version 2       14.11.1988      Klaus Petry
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE mamsneg       : 890501.9203__.941201
H*/
/*
	For the definition of mamsneg please refer to the header file _matr1.h.
*/
