/*M
.SH NAME
manrcol - matrix number of columns (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single manrcol(M)
matrix M;

.SH DESCRIPTION
manrcol() returns the number of columns of the matrix M.
M*/
/*H
	Version 1       03.05.1988      Klaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE manrcol       : 890501.941201
H*/
/*
	For the definition of manrcol please refer to the header file _matr1.h.
*/
