/*M
.SH NAME
mapicons1 - matrix of polynomials over integers, construction 1 (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix mapicons1(r, n)
single r, n;

.SH DESCRIPTION
mapicons1() returns the n-dimensional unity matrix of
polynomials in r variables over integers.

M*/
/*H
	Version 1       08.06.1988      Klaus Petry
	Version 2       02.09.1989      Klaus Petry     Macro
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE mapicons1     : 890501.941201
H*/
/*
	For the definition of mapicons1 please refer to the header file _matr1.h.
*/
