/*M
.SH NAME
mapmicons1 - matrix of polynomials over modular integers, construction 1 (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix mapmicons1(r, m, n)
single r;
int m;
single n;

.SH DESCRIPTION
mapmicons1() returns the n-dimensional unity matrix of
polynomials in r variables over Z/mZ.

M*/
/*H
	Version 1       31.01.1992      Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE mapmicons1    : 920331.941201
H*/
/*
	For the definition of mapmicons1 please refer to the header file _matr1.h.
*/
