/*M
.SH NAME
maprcons1 - matrix of polynomials over the rational numbers, construction 1 (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

matrix maprcons1(r, n)
single r, n;

.SH DESCRIPTION
maprcons1() returns the n-dimensional unity matrix of
polynomials in r variables over the rational numbers.

M*/
/*H
	Version 1       28.07.1988      Klaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE maprcons1     : 890501.941201
H*/
/*
	For the definition of maprcons1 please refer to the header file _matr1.h.
*/
