/*M
.SH NAME
marchpol - matrix of rational numbers, characteristic polynomial (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

pol marchpol(M)
matrix M;

.SH DESCRIPTION
marchpol() returns the characteristic polynomial of the matrix M.

.PP
.TP 4
.B M
is a square matrix of rational numbers.
M*/

/*H
	Version 1       16.06.1988      Klaus Petry
	Version 2       14.11.1988      Klaus Petry
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE marchpol      : 890501.941201
H*/
/*
	For the definition of marchpol please refer to the header file _matr1.h.
*/
