/*M
.SH NAME
maselel - matrix select element (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

obj maselel(M, m, n)
matrix M;
single m, n;

.SH DESCRIPTION
maselel() returns the element at position (m,n) of the matrix M.
M*/


/*H
	Version 1       02.02.1989      Klaus Petry  
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE maselel       : 890501.8906__.941201
H*/
/*
	For the definition of maselel please refer to the header file _matr1.h.
*/
