/*M
.SH NAME
putmapr - put matrix of polynomials over the rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putmapr(r, M, V)
single r;
matrix M;
list V;

.SH DESCRIPTION
putmapr() is equivalent to fputmapr() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmapr
M*/




/*H
	Version 1       28.07.1988      Klaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmapr       : 890501.941201
H*/
/*
	For the definition of putmapr please refer to the header file _matr1.h.
*/
