/*M
.SH NAME
putmapmi - put matrix of polynomials over modular integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putmapmi(r, m, M, V)
single r;
int m;
matrix M;
list V;

.SH DESCRIPTION
putmapmi() is equivalent to fputmapmi() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmapmi
M*/




/*H
	Version 1       31.01.1992      Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmapmi      : 920331.941201
H*/
/*
	For the definition of putmapmi please refer to the header file _matr1.h.
*/
