/*M
.SH NAME
putmar - put matrix of rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putmar(M)
matrix M;

.SH DESCRIPTION
putmar() is equivalent to fputmar() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmar
M*/




/*H
	Version 1       07.06.1988      Klaus Petry
	Version 2       03.11.1988      Klaus Petry
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmar        : 890501.941201
H*/
/*
	For the definition of putmar please refer to the header file _matr1.h.
*/
