/*M
.SH NAME
putmaflfx - put matrix of floating point numbers by fix point (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putmaflfx(M, v, n)
matrix M;
single v, n;

.SH DESCRIPTION
putmaflfx() is equivalent to fputmaflfx() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmaflfx
M*/





/*H
	Version 1	12.11.1992	Josef Gebel
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmaflfx     : 921130.941201
H*/
/*
	For the definition of putmaflfx please refer to the header file _matr1.h.
*/
