/*M
.SH NAME
putmai - put matrix of integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putmai(M)
matrix M;

.SH DESCRIPTION
putmai() is equivalent to fputmai() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmai
M*/




/*H
	Version 1       07.06.1988      Klaus Petry
	Version 2       03.11.1988      Klaus Petry
	Version 3	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmai        : 890501.941201
H*/
/*
	For the definition of putmai please refer to the header file _matr1.h.
*/
