/*M
.SH NAME
putmams - put matrix of modular singles (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putmams(m, M)
single m;
matrix M;

.SH DESCRIPTION
putmams() is equivalent to fputmams() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmams
M*/




/*H
	Version 1       20.07.1988      Klaus Petry
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmams       : 890501.9203__.941201
H*/
/*
	For the definition of putmams please refer to the header file _matr1.h.
*/
