/*M
.SH NAME
putmami - put matrix of modular integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putmami(m, M)
int m;
matrix M;

.SH DESCRIPTION
putmami() is equivalent to fputmami() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmami
M*/




/*H
	Version 1       31.01.1992      Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmami       : 920331.941201
H*/
/*
	For the definition of putmami please refer to the header file _matr1.h.
*/
