/*M
.SH NAME
putvecpmi - put vector of polynomials over modular integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putvecpmi(r, m, V, VL)
single r;
int m;
vec V;
list VL;

.SH DESCRIPTION
putvecpmi() is equivalent to fputvecpmi() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecpmi
M*/




/*H
	Version 1       31.01.1992      Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecpmi     : 920331.941201
H*/
/*
	For the definition of putvecpmi please refer to the header file _matr1.h.
*/
