/*M
.SH NAME
putvecpr - put vector of polynomials over the rational numbers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putvecpr(r, V, VL)
single r;
vec V;
list VL;

.SH DESCRIPTION
putvecpr() is equivalent to fputvecpr() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecpr
M*/




/*H
	Version 1       01.03.1988      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecpr      : 890601.941201
H*/
/*
	For the definition of putvecpr please refer to the header file _matr1.h.
*/
