/*M
.SH NAME
putvecpms - put vector of polynomials over modular singles (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putvecpms(r, m, V, VL)
single r, m;
vec V;
list VL;

.SH DESCRIPTION
putvecpms() is equivalent to fputvecpms() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecpms
M*/




/*H
	Version 1       01.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecpms     : 890601.9203__.941201
H*/
/*
	For the definition of putvecpms please refer to the header file _matr1.h.
*/
