/*M
.SH NAME
putvecms - put vector of modular singles (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putvecms(m, V)
single m;
vec V;

.SH DESCRIPTION
putvecms() is equivalent to fputvecms() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecms
M*/




/*H
	Version 1       01.03.1988      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecms      : 890601.9203__.941201
H*/
/*
	For the definition of putvecms please refer to the header file _matr1.h.
*/
