/*M
.SH NAME
putveci - put vector of integers (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

single putveci(V)
vec V;

.SH DESCRIPTION
putveci() is equivalent to fputveci() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputveci
M*/




/*H
	Version 1       01.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putveci       : 890601.941201
H*/
/*
	For the definition of putveci please refer to the header file _matr1.h.
*/
