/*M
.SH NAME
vecidif - vector of integers, difference (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecidif(U, V)
vec U, V;

.SH DESCRIPTION
vecidif() returns the vector U-V.

.PP
.TP 4
.B U, V
are vectors of integers. 
U and V must have equal length.
M*/

/*H
	Version 1       25.08.1988      Klaus Petry
	Version 1.2     15.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecidif       : 890601.941201
H*/
/*
	For the definition of vecidif please refer to the header file _matr1.h.
*/
