/*M
.SH NAME
vecmineg - vector of modular integers, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecmineg(m, V)
int m;
vec V;

.SH DESCRIPTION
vecmineg() returns the vector -V.

.PP
.TP 4
.B V
is a vector over Z/mZ.
M*/
/*H
	Version 1       31.01.1992     Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecmineg      : 920331.941201
H*/
/*
	For the definition of vecmineg please refer to the header file _matr1.h.
*/
