/*M
.SH NAME
vecmsneg - vector of modular singles, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecmsneg(m, V)
single m;
vec V;

.SH DESCRIPTION
vecmsneg() returns the vector -V.

.PP
.TP 4
.B V
is a vector over Z/mZ.
M*/
/*H
	Version 1       15.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecmsneg      : 890601.9203__.941201
H*/
/*
	For the definition of vecmsneg please refer to the header file _matr1.h.
*/
