/*M
.SH NAME
vecpidif - vector of polynomials over integers, difference (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecpidif(r, U, V)
single r;
vec U, V;

.SH DESCRIPTION
vecpidif() returns the vector U-V.

.PP
.TP 4
.B U, V
are vectors of polynomials in r variables over integers.
U and V must have equal length.
M*/


/*H
	Version 1       15.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecpidif      : 890601.941201
H*/
/*
	For the definition of vecpidif please refer to the header file _matr1.h.
*/
