/*M
.SH NAME
vecprneg - vector of polynomials over the rational numbers, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecprneg(r, V)
single r;
vec V;

.SH DESCRIPTION
vecprneg() returns the vector -V.

.PP
.TP 4
.B V
is a vector of polynomials in r variables over the rational numbers.
M*/
/*H
	Version 1       15.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecprneg      : 890601.941201
H*/
/*
	For the definition of vecprneg please refer to the header file _matr1.h.
*/
