/*M
.SH NAME
vecpineg - vector of polynomials over integers, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecpineg(r, V)
single r;
vec V;

.SH DESCRIPTION
vecpineg() returns the vector -V.

.PP
.TP 4
.B V
is a vector of polynomials in r variables over integers.
M*/
/*H
	Version 1       15.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecpineg      : 890601.941201
H*/
/*
	For the definition of vecpineg please refer to the header file _matr1.h.
*/
