/*M
.SH NAME
vecpmineg - vector of polynomials over modular integers, negation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecpmineg(r, m, V)
single r;
int m;
vec V;

.SH DESCRIPTION
vecpmineg() returns the vector -V.

.PP
.TP 4
.B V
is a vector of polynomials in r variables over Z/mZ.
M*/
/*H
	Version 1       31.01.1992      Bernd Mayr
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecpmineg     : 920331.941201
H*/
/*
	For the definition of vecpmineg please refer to the header file _matr1.h.
*/
