/*M
.SH NAME
vecrdif - vector of rational numbers, difference (MACRO)

.SH SYNOPSIS
.nf
#include<_matr1.h>

vec vecrdif(U, V)
vec U, V;

.SH DESCRIPTION
vecrdif() returns the vector U-V.

.PP
.TP 4
.B U, V
are vectors of rational numbers.
U and V must have equal length.
M*/

/*H
	Version 1       15.03.1989      U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE vecrdif       : 890601.941201
H*/
/*
	For the definition of vecrdif please refer to the header file _matr1.h.
*/
