/*M
.SH NAME
itopi - integer to polynomial over integer

.SH SYNOPSIS
.nf
#include<_pol1.h>

pol itopi(r, A)  
single r; 
int A;

.SH DESCRIPTION
.TP 4
.B r
is an integer number, 0 <= r < BASIS.
.PP
itopi returns A as a constant polynomial in r variables.

M*/

/*H    
					
	Version 1       19.04.1993     	Marc Conrad
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE itopi         : 930531.941201
H*/
/*
	For the definition of itopi please refer to the header file _pol1.h.
*/
