/*M
.SH NAME
getgf2elb - get Galois-field with characteristic 2 element, bit  (MACRO)

.SH SYNOPSIS
.nf
#include<_arith2.h>

gf2el getgf2elb(G)  
obj G;


.SH DESCRIPTION
getgf2elb() is equivalent to fgetgf2elb() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetgf2elb
M*/
/*H
	Version 1       24.10.1995	U.Schneiders
   DATE getgf2elb     : 951201
H*/
/*
	For the definition of getgf2elb please refer to the header file _arith2.h.
*/
