/*M
.SH NAME
putgf2elb - put Galois-field with characteristic 2 element, bit  (MACRO)

.SH SYNOPSIS
.nf
#include<_arith2.h>

single putgf2elb(a)  
gf2el a;


.SH DESCRIPTION
putgf2elb() is equivalent to fputgf2elb() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputgf2elb
M*/
/*H
	Version 1       28.11.1995	U.Schmitt
   DATE putgf2elb     : 951201
H*/
/*
	For the definition of putgf2elb please refer to the header file _arith2.h.
*/
