/*M
.SH NAME
sbtoudpm2 - special bit-representation to univariate dense polynomial over modular 2
(MACRO)

.SH SYNOPSIS
.nf
#include<_arith2.h>

pol sbtoudpm2(P)  
obj a;

.SH DESCRIPTION
.TP 4
.B P
is an univariate polynomial over Z/2Z in special bit-representation.
.PP
sbtoudpm2 returns P as an univariate polynomial over Z/2Z in dense representation.
 
.SH SEE ALSO
udpm2tosb

M*/
                                                   
/*H
	Version 1       03.09.1993	U.Schneiders
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE sbtoudpm2     : 931130.941201
H*/
/*
	For the definition of sbtoudpm2 please refer to the header file _arith2.h.
*/
