include ../../Makefile.flags


all: \
	absvalex.o \
	caifact.o \
	calc_GF2bit.o \
	calc_actec.o \
	calc_actmod.o \
	calc_actnf.o \
	calc_aftopr.o \
	calc_and.o \
	calc_arepli.o \
	calc_aval.o \
	calc_basmwg.o \
	calc_binom.o \
	calc_bitrans.o \
	calc_ceil.o \
	calc_chcoef.o \
	calc_chinrem.o \
	calc_chpol.o \
	calc_clnum.o \
	calc_coef.o \
	calc_cond.o \
	calc_conjug.o \
	calc_cons.o \
	calc_cont.o \
	calc_cper.o \
	calc_declaw.o \
	calc_deg.o \
	calc_denom.o \
	calc_deriv.o \
	calc_derivL.o \
	calc_det.o \
	calc_dif.o \
	calc_discec.o \
	calc_discnf.o \
	calc_disk.o \
	calc_dmcon.o \
	calc_ec.o \
	calc_eccoef.o \
	calc_ecinf.o \
	calc_egcd.o \
	calc_eival.o \
	calc_elform.o \
	calc_elog.o \
	calc_elsubst.o \
	calc_equ.o \
	calc_exp.o \
	calc_expo.o \
	calc_faintp.o \
	calc_fakt.o \
	calc_floor.o \
	calc_fltoi.o \
	calc_fp.o \
	calc_froot.o \
	calc_ge.o \
	calc_geq.o \
	calc_gf.o \
	calc_gftopol.o \
	calc_ggt.o \
	calc_herm.o \
	calc_imag.o \
	calc_intbas.o \
	calc_intcoef.o \
	calc_integr.o \
	calc_iphi.o \
	calc_ippcon.o \
	calc_irpgen.o \
	calc_ispprime.o \
	calc_isprime.o \
	calc_isptec.o \
	calc_isqrt.o \
	calc_jacsym.o \
	calc_jinv.o \
	calc_kgv.o \
	calc_le.o \
	calc_leq.o \
	calc_linequ.o \
	calc_ln.o \
	calc_log10.o \
	calc_log2.o \
	calc_m.o \
	calc_mam2.o \
	calc_max.o \
	calc_mcoef.o \
	calc_mex.o \
	calc_min.o \
	calc_minim.o \
	calc_minor.o \
	calc_mod.o \
	calc_mtoi.o \
	calc_mval.o \
	calc_neg.o \
	calc_nequ.o \
	calc_nf.o \
	calc_nftopol.o \
	calc_norm.o \
	calc_np.o \
	calc_npfe.o \
	calc_nthei.o \
	calc_ntpair.o \
	calc_num.o \
	calc_or.o \
	calc_ord.o \
	calc_ordtsg.o \
	calc_pconstr.o \
	calc_pec.o \
	calc_pfakt.o \
	calc_pgen.o \
	calc_ppcon.o \
	calc_prim.o \
	calc_proot.o \
	calc_prtoaf.o \
	calc_ptcoef.o \
	calc_putGF2b.o \
	calc_putb.o \
	calc_putbits.o \
	calc_puthex.o \
	calc_puto.o \
	calc_putoct.o \
	calc_quot.o \
	calc_real.o \
	calc_red.o \
	calc_reg.o \
	calc_relcln.o \
	calc_resul.o \
	calc_rk.o \
	calc_rk2d.o \
	calc_rkbsd.o \
	calc_rkg2d.o \
	calc_root.o \
	calc_rper.o \
	calc_sfp.o \
	calc_sgn.o \
	calc_sgnfeq.o \
	calc_skalar.o \
	calc_sort.o \
	calc_sqrt.o \
	calc_stfkt.o \
	calc_sum.o \
	calc_swnf.o \
	calc_taalg.o \
	calc_tav.o \
	calc_tofl.o \
	calc_tors.o \
	calc_trace.o \
	calc_transp.o \
	calc_trig.o \
	calc_unit.o \
	calc_vcoef.o \
	calc_whei.o \
	calc_zmcon.o \
	calc_zvcon.o \
	carrqnf1.o \
	casi_ecgnp.o \
	casi_ecnpscf.o \
	casi_f1root.o \
	casi_irpgen.o \
	casi_np.o \
	ecgf2npcasv.o \
	ecrbtco_old.o \
	ecrsnftoic_o.o \
	ecrtoic_o.o \
	eval.o \
	ranlib


clean:
	rm -f *~
	rm -f absvalex.o
	rm -f caifact.o
	rm -f calc_GF2bit.o
	rm -f calc_actec.o
	rm -f calc_actmod.o
	rm -f calc_actnf.o
	rm -f calc_aftopr.o
	rm -f calc_and.o
	rm -f calc_arepli.o
	rm -f calc_aval.o
	rm -f calc_basmwg.o
	rm -f calc_binom.o
	rm -f calc_bitrans.o
	rm -f calc_ceil.o
	rm -f calc_chcoef.o
	rm -f calc_chinrem.o
	rm -f calc_chpol.o
	rm -f calc_clnum.o
	rm -f calc_coef.o
	rm -f calc_cond.o
	rm -f calc_conjug.o
	rm -f calc_cons.o
	rm -f calc_cont.o
	rm -f calc_cper.o
	rm -f calc_declaw.o
	rm -f calc_deg.o
	rm -f calc_denom.o
	rm -f calc_deriv.o
	rm -f calc_derivL.o
	rm -f calc_det.o
	rm -f calc_dif.o
	rm -f calc_discec.o
	rm -f calc_discnf.o
	rm -f calc_disk.o
	rm -f calc_dmcon.o
	rm -f calc_ec.o
	rm -f calc_eccoef.o
	rm -f calc_ecinf.o
	rm -f calc_egcd.o
	rm -f calc_eival.o
	rm -f calc_elform.o
	rm -f calc_elog.o
	rm -f calc_elsubst.o
	rm -f calc_equ.o
	rm -f calc_exp.o
	rm -f calc_expo.o
	rm -f calc_faintp.o
	rm -f calc_fakt.o
	rm -f calc_floor.o
	rm -f calc_fltoi.o
	rm -f calc_fp.o
	rm -f calc_froot.o
	rm -f calc_ge.o
	rm -f calc_geq.o
	rm -f calc_gf.o
	rm -f calc_gftopol.o
	rm -f calc_ggt.o
	rm -f calc_herm.o
	rm -f calc_imag.o
	rm -f calc_intbas.o
	rm -f calc_intcoef.o
	rm -f calc_integr.o
	rm -f calc_iphi.o
	rm -f calc_ippcon.o
	rm -f calc_irpgen.o
	rm -f calc_ispprime.o
	rm -f calc_isprime.o
	rm -f calc_isptec.o
	rm -f calc_isqrt.o
	rm -f calc_jacsym.o
	rm -f calc_jinv.o
	rm -f calc_kgv.o
	rm -f calc_le.o
	rm -f calc_leq.o
	rm -f calc_linequ.o
	rm -f calc_ln.o
	rm -f calc_log10.o
	rm -f calc_log2.o
	rm -f calc_m.o
	rm -f calc_mam2.o
	rm -f calc_max.o
	rm -f calc_mcoef.o
	rm -f calc_mex.o
	rm -f calc_min.o
	rm -f calc_minim.o
	rm -f calc_minor.o
	rm -f calc_mod.o
	rm -f calc_mtoi.o
	rm -f calc_mval.o
	rm -f calc_neg.o
	rm -f calc_nequ.o
	rm -f calc_nf.o
	rm -f calc_nftopol.o
	rm -f calc_norm.o
	rm -f calc_np.o
	rm -f calc_npfe.o
	rm -f calc_nthei.o
	rm -f calc_ntpair.o
	rm -f calc_num.o
	rm -f calc_or.o
	rm -f calc_ord.o
	rm -f calc_ordtsg.o
	rm -f calc_pconstr.o
	rm -f calc_pec.o
	rm -f calc_pfakt.o
	rm -f calc_pgen.o
	rm -f calc_ppcon.o
	rm -f calc_prim.o
	rm -f calc_proot.o
	rm -f calc_prtoaf.o
	rm -f calc_ptcoef.o
	rm -f calc_putGF2b.o
	rm -f calc_putb.o
	rm -f calc_putbits.o
	rm -f calc_puthex.o
	rm -f calc_puto.o
	rm -f calc_putoct.o
	rm -f calc_quot.o
	rm -f calc_real.o
	rm -f calc_red.o
	rm -f calc_reg.o
	rm -f calc_relcln.o
	rm -f calc_resul.o
	rm -f calc_rk.o
	rm -f calc_rk2d.o
	rm -f calc_rkbsd.o
	rm -f calc_rkg2d.o
	rm -f calc_root.o
	rm -f calc_rper.o
	rm -f calc_sfp.o
	rm -f calc_sgn.o
	rm -f calc_sgnfeq.o
	rm -f calc_skalar.o
	rm -f calc_sort.o
	rm -f calc_sqrt.o
	rm -f calc_stfkt.o
	rm -f calc_sum.o
	rm -f calc_swnf.o
	rm -f calc_taalg.o
	rm -f calc_tav.o
	rm -f calc_tofl.o
	rm -f calc_tors.o
	rm -f calc_trace.o
	rm -f calc_transp.o
	rm -f calc_trig.o
	rm -f calc_unit.o
	rm -f calc_vcoef.o
	rm -f calc_whei.o
	rm -f calc_zmcon.o
	rm -f calc_zvcon.o
	rm -f carrqnf1.o
	rm -f casi_ecgnp.o
	rm -f casi_ecnpscf.o
	rm -f casi_f1root.o
	rm -f casi_irpgen.o
	rm -f casi_np.o
	rm -f ecgf2npcasv.o
	rm -f ecrbtco_old.o
	rm -f ecrsnftoic_o.o
	rm -f ecrtoic_o.o
	rm -f eval.o


veryclean: clean
	rm -f ../lib/libsimre.a



absvalex.o: \
	absvalex.S
	../../bin/preV3_1.x absvalex.S absvalex.P
	../../bin/preproc.x absvalex.P absvalex.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o absvalex.o absvalex.c
	rm -f absvalex.c absvalex.P
	ar rv ../lib/libsimre.a absvalex.o

caifact.o: \
	caifact.S
	../../bin/preV3_1.x caifact.S caifact.P
	../../bin/preproc.x caifact.P caifact.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o caifact.o caifact.c
	rm -f caifact.c caifact.P
	ar rv ../lib/libsimre.a caifact.o

calc_GF2bit.o: \
	calc_GF2bit.S
	../../bin/preV3_1.x calc_GF2bit.S calc_GF2bit.P
	../../bin/preproc.x calc_GF2bit.P calc_GF2bit.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_GF2bit.o calc_GF2bit.c
	rm -f calc_GF2bit.c calc_GF2bit.P
	ar rv ../lib/libsimre.a calc_GF2bit.o

calc_actec.o: \
	calc_actec.S
	../../bin/preV3_1.x calc_actec.S calc_actec.P
	../../bin/preproc.x calc_actec.P calc_actec.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_actec.o calc_actec.c
	rm -f calc_actec.c calc_actec.P
	ar rv ../lib/libsimre.a calc_actec.o

calc_actmod.o: \
	calc_actmod.S
	../../bin/preV3_1.x calc_actmod.S calc_actmod.P
	../../bin/preproc.x calc_actmod.P calc_actmod.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_actmod.o calc_actmod.c
	rm -f calc_actmod.c calc_actmod.P
	ar rv ../lib/libsimre.a calc_actmod.o

calc_actnf.o: \
	calc_actnf.S
	../../bin/preV3_1.x calc_actnf.S calc_actnf.P
	../../bin/preproc.x calc_actnf.P calc_actnf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_actnf.o calc_actnf.c
	rm -f calc_actnf.c calc_actnf.P
	ar rv ../lib/libsimre.a calc_actnf.o

calc_aftopr.o: \
	calc_aftopr.S
	../../bin/preV3_1.x calc_aftopr.S calc_aftopr.P
	../../bin/preproc.x calc_aftopr.P calc_aftopr.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_aftopr.o calc_aftopr.c
	rm -f calc_aftopr.c calc_aftopr.P
	ar rv ../lib/libsimre.a calc_aftopr.o

calc_and.o: \
	calc_and.S
	../../bin/preV3_1.x calc_and.S calc_and.P
	../../bin/preproc.x calc_and.P calc_and.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_and.o calc_and.c
	rm -f calc_and.c calc_and.P
	ar rv ../lib/libsimre.a calc_and.o

calc_arepli.o: \
	calc_arepli.S
	../../bin/preV3_1.x calc_arepli.S calc_arepli.P
	../../bin/preproc.x calc_arepli.P calc_arepli.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_arepli.o calc_arepli.c
	rm -f calc_arepli.c calc_arepli.P
	ar rv ../lib/libsimre.a calc_arepli.o

calc_aval.o: \
	calc_aval.S
	../../bin/preV3_1.x calc_aval.S calc_aval.P
	../../bin/preproc.x calc_aval.P calc_aval.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_aval.o calc_aval.c
	rm -f calc_aval.c calc_aval.P
	ar rv ../lib/libsimre.a calc_aval.o

calc_basmwg.o: \
	calc_basmwg.S
	../../bin/preV3_1.x calc_basmwg.S calc_basmwg.P
	../../bin/preproc.x calc_basmwg.P calc_basmwg.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_basmwg.o calc_basmwg.c
	rm -f calc_basmwg.c calc_basmwg.P
	ar rv ../lib/libsimre.a calc_basmwg.o

calc_binom.o: \
	calc_binom.S
	../../bin/preV3_1.x calc_binom.S calc_binom.P
	../../bin/preproc.x calc_binom.P calc_binom.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_binom.o calc_binom.c
	rm -f calc_binom.c calc_binom.P
	ar rv ../lib/libsimre.a calc_binom.o

calc_bitrans.o: \
	calc_bitrans.S
	../../bin/preV3_1.x calc_bitrans.S calc_bitrans.P
	../../bin/preproc.x calc_bitrans.P calc_bitrans.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_bitrans.o calc_bitrans.c
	rm -f calc_bitrans.c calc_bitrans.P
	ar rv ../lib/libsimre.a calc_bitrans.o

calc_ceil.o: \
	calc_ceil.S
	../../bin/preV3_1.x calc_ceil.S calc_ceil.P
	../../bin/preproc.x calc_ceil.P calc_ceil.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ceil.o calc_ceil.c
	rm -f calc_ceil.c calc_ceil.P
	ar rv ../lib/libsimre.a calc_ceil.o

calc_chcoef.o: \
	calc_chcoef.S
	../../bin/preV3_1.x calc_chcoef.S calc_chcoef.P
	../../bin/preproc.x calc_chcoef.P calc_chcoef.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_chcoef.o calc_chcoef.c
	rm -f calc_chcoef.c calc_chcoef.P
	ar rv ../lib/libsimre.a calc_chcoef.o

calc_chinrem.o: \
	calc_chinrem.S
	../../bin/preV3_1.x calc_chinrem.S calc_chinrem.P
	../../bin/preproc.x calc_chinrem.P calc_chinrem.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_chinrem.o calc_chinrem.c
	rm -f calc_chinrem.c calc_chinrem.P
	ar rv ../lib/libsimre.a calc_chinrem.o

calc_chpol.o: \
	calc_chpol.S
	../../bin/preV3_1.x calc_chpol.S calc_chpol.P
	../../bin/preproc.x calc_chpol.P calc_chpol.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_chpol.o calc_chpol.c
	rm -f calc_chpol.c calc_chpol.P
	ar rv ../lib/libsimre.a calc_chpol.o

calc_clnum.o: \
	calc_clnum.S
	../../bin/preV3_1.x calc_clnum.S calc_clnum.P
	../../bin/preproc.x calc_clnum.P calc_clnum.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_clnum.o calc_clnum.c
	rm -f calc_clnum.c calc_clnum.P
	ar rv ../lib/libsimre.a calc_clnum.o

calc_coef.o: \
	calc_coef.S
	../../bin/preV3_1.x calc_coef.S calc_coef.P
	../../bin/preproc.x calc_coef.P calc_coef.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_coef.o calc_coef.c
	rm -f calc_coef.c calc_coef.P
	ar rv ../lib/libsimre.a calc_coef.o

calc_cond.o: \
	calc_cond.S
	../../bin/preV3_1.x calc_cond.S calc_cond.P
	../../bin/preproc.x calc_cond.P calc_cond.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_cond.o calc_cond.c
	rm -f calc_cond.c calc_cond.P
	ar rv ../lib/libsimre.a calc_cond.o

calc_conjug.o: \
	calc_conjug.S
	../../bin/preV3_1.x calc_conjug.S calc_conjug.P
	../../bin/preproc.x calc_conjug.P calc_conjug.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_conjug.o calc_conjug.c
	rm -f calc_conjug.c calc_conjug.P
	ar rv ../lib/libsimre.a calc_conjug.o

calc_cons.o: \
	calc_cons.S
	../../bin/preV3_1.x calc_cons.S calc_cons.P
	../../bin/preproc.x calc_cons.P calc_cons.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_cons.o calc_cons.c
	rm -f calc_cons.c calc_cons.P
	ar rv ../lib/libsimre.a calc_cons.o

calc_cont.o: \
	calc_cont.S
	../../bin/preV3_1.x calc_cont.S calc_cont.P
	../../bin/preproc.x calc_cont.P calc_cont.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_cont.o calc_cont.c
	rm -f calc_cont.c calc_cont.P
	ar rv ../lib/libsimre.a calc_cont.o

calc_cper.o: \
	calc_cper.S
	../../bin/preV3_1.x calc_cper.S calc_cper.P
	../../bin/preproc.x calc_cper.P calc_cper.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_cper.o calc_cper.c
	rm -f calc_cper.c calc_cper.P
	ar rv ../lib/libsimre.a calc_cper.o

calc_declaw.o: \
	calc_declaw.S
	../../bin/preV3_1.x calc_declaw.S calc_declaw.P
	../../bin/preproc.x calc_declaw.P calc_declaw.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_declaw.o calc_declaw.c
	rm -f calc_declaw.c calc_declaw.P
	ar rv ../lib/libsimre.a calc_declaw.o

calc_deg.o: \
	calc_deg.S
	../../bin/preV3_1.x calc_deg.S calc_deg.P
	../../bin/preproc.x calc_deg.P calc_deg.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_deg.o calc_deg.c
	rm -f calc_deg.c calc_deg.P
	ar rv ../lib/libsimre.a calc_deg.o

calc_denom.o: \
	calc_denom.S
	../../bin/preV3_1.x calc_denom.S calc_denom.P
	../../bin/preproc.x calc_denom.P calc_denom.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_denom.o calc_denom.c
	rm -f calc_denom.c calc_denom.P
	ar rv ../lib/libsimre.a calc_denom.o

calc_deriv.o: \
	calc_deriv.S
	../../bin/preV3_1.x calc_deriv.S calc_deriv.P
	../../bin/preproc.x calc_deriv.P calc_deriv.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_deriv.o calc_deriv.c
	rm -f calc_deriv.c calc_deriv.P
	ar rv ../lib/libsimre.a calc_deriv.o

calc_derivL.o: \
	calc_derivL.S
	../../bin/preV3_1.x calc_derivL.S calc_derivL.P
	../../bin/preproc.x calc_derivL.P calc_derivL.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_derivL.o calc_derivL.c
	rm -f calc_derivL.c calc_derivL.P
	ar rv ../lib/libsimre.a calc_derivL.o

calc_det.o: \
	calc_det.S
	../../bin/preV3_1.x calc_det.S calc_det.P
	../../bin/preproc.x calc_det.P calc_det.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_det.o calc_det.c
	rm -f calc_det.c calc_det.P
	ar rv ../lib/libsimre.a calc_det.o

calc_dif.o: \
	calc_dif.S
	../../bin/preV3_1.x calc_dif.S calc_dif.P
	../../bin/preproc.x calc_dif.P calc_dif.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_dif.o calc_dif.c
	rm -f calc_dif.c calc_dif.P
	ar rv ../lib/libsimre.a calc_dif.o

calc_discec.o: \
	calc_discec.S
	../../bin/preV3_1.x calc_discec.S calc_discec.P
	../../bin/preproc.x calc_discec.P calc_discec.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_discec.o calc_discec.c
	rm -f calc_discec.c calc_discec.P
	ar rv ../lib/libsimre.a calc_discec.o

calc_discnf.o: \
	calc_discnf.S
	../../bin/preV3_1.x calc_discnf.S calc_discnf.P
	../../bin/preproc.x calc_discnf.P calc_discnf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_discnf.o calc_discnf.c
	rm -f calc_discnf.c calc_discnf.P
	ar rv ../lib/libsimre.a calc_discnf.o

calc_disk.o: \
	calc_disk.S
	../../bin/preV3_1.x calc_disk.S calc_disk.P
	../../bin/preproc.x calc_disk.P calc_disk.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_disk.o calc_disk.c
	rm -f calc_disk.c calc_disk.P
	ar rv ../lib/libsimre.a calc_disk.o

calc_dmcon.o: \
	calc_dmcon.S
	../../bin/preV3_1.x calc_dmcon.S calc_dmcon.P
	../../bin/preproc.x calc_dmcon.P calc_dmcon.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_dmcon.o calc_dmcon.c
	rm -f calc_dmcon.c calc_dmcon.P
	ar rv ../lib/libsimre.a calc_dmcon.o

calc_ec.o: \
	calc_ec.S
	../../bin/preV3_1.x calc_ec.S calc_ec.P
	../../bin/preproc.x calc_ec.P calc_ec.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ec.o calc_ec.c
	rm -f calc_ec.c calc_ec.P
	ar rv ../lib/libsimre.a calc_ec.o

calc_eccoef.o: \
	calc_eccoef.S
	../../bin/preV3_1.x calc_eccoef.S calc_eccoef.P
	../../bin/preproc.x calc_eccoef.P calc_eccoef.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_eccoef.o calc_eccoef.c
	rm -f calc_eccoef.c calc_eccoef.P
	ar rv ../lib/libsimre.a calc_eccoef.o

calc_ecinf.o: \
	calc_ecinf.S
	../../bin/preV3_1.x calc_ecinf.S calc_ecinf.P
	../../bin/preproc.x calc_ecinf.P calc_ecinf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ecinf.o calc_ecinf.c
	rm -f calc_ecinf.c calc_ecinf.P
	ar rv ../lib/libsimre.a calc_ecinf.o

calc_egcd.o: \
	calc_egcd.S
	../../bin/preV3_1.x calc_egcd.S calc_egcd.P
	../../bin/preproc.x calc_egcd.P calc_egcd.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_egcd.o calc_egcd.c
	rm -f calc_egcd.c calc_egcd.P
	ar rv ../lib/libsimre.a calc_egcd.o

calc_eival.o: \
	calc_eival.S
	../../bin/preV3_1.x calc_eival.S calc_eival.P
	../../bin/preproc.x calc_eival.P calc_eival.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_eival.o calc_eival.c
	rm -f calc_eival.c calc_eival.P
	ar rv ../lib/libsimre.a calc_eival.o

calc_elform.o: \
	calc_elform.S
	../../bin/preV3_1.x calc_elform.S calc_elform.P
	../../bin/preproc.x calc_elform.P calc_elform.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_elform.o calc_elform.c
	rm -f calc_elform.c calc_elform.P
	ar rv ../lib/libsimre.a calc_elform.o

calc_elog.o: \
	calc_elog.S
	../../bin/preV3_1.x calc_elog.S calc_elog.P
	../../bin/preproc.x calc_elog.P calc_elog.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_elog.o calc_elog.c
	rm -f calc_elog.c calc_elog.P
	ar rv ../lib/libsimre.a calc_elog.o

calc_elsubst.o: \
	calc_elsubst.S
	../../bin/preV3_1.x calc_elsubst.S calc_elsubst.P
	../../bin/preproc.x calc_elsubst.P calc_elsubst.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_elsubst.o calc_elsubst.c
	rm -f calc_elsubst.c calc_elsubst.P
	ar rv ../lib/libsimre.a calc_elsubst.o

calc_equ.o: \
	calc_equ.S
	../../bin/preV3_1.x calc_equ.S calc_equ.P
	../../bin/preproc.x calc_equ.P calc_equ.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_equ.o calc_equ.c
	rm -f calc_equ.c calc_equ.P
	ar rv ../lib/libsimre.a calc_equ.o

calc_exp.o: \
	calc_exp.S
	../../bin/preV3_1.x calc_exp.S calc_exp.P
	../../bin/preproc.x calc_exp.P calc_exp.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_exp.o calc_exp.c
	rm -f calc_exp.c calc_exp.P
	ar rv ../lib/libsimre.a calc_exp.o

calc_expo.o: \
	calc_expo.S
	../../bin/preV3_1.x calc_expo.S calc_expo.P
	../../bin/preproc.x calc_expo.P calc_expo.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_expo.o calc_expo.c
	rm -f calc_expo.c calc_expo.P
	ar rv ../lib/libsimre.a calc_expo.o

calc_faintp.o: \
	calc_faintp.S
	../../bin/preV3_1.x calc_faintp.S calc_faintp.P
	../../bin/preproc.x calc_faintp.P calc_faintp.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_faintp.o calc_faintp.c
	rm -f calc_faintp.c calc_faintp.P
	ar rv ../lib/libsimre.a calc_faintp.o

calc_fakt.o: \
	calc_fakt.S
	../../bin/preV3_1.x calc_fakt.S calc_fakt.P
	../../bin/preproc.x calc_fakt.P calc_fakt.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_fakt.o calc_fakt.c
	rm -f calc_fakt.c calc_fakt.P
	ar rv ../lib/libsimre.a calc_fakt.o

calc_floor.o: \
	calc_floor.S
	../../bin/preV3_1.x calc_floor.S calc_floor.P
	../../bin/preproc.x calc_floor.P calc_floor.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_floor.o calc_floor.c
	rm -f calc_floor.c calc_floor.P
	ar rv ../lib/libsimre.a calc_floor.o

calc_fltoi.o: \
	calc_fltoi.S
	../../bin/preV3_1.x calc_fltoi.S calc_fltoi.P
	../../bin/preproc.x calc_fltoi.P calc_fltoi.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_fltoi.o calc_fltoi.c
	rm -f calc_fltoi.c calc_fltoi.P
	ar rv ../lib/libsimre.a calc_fltoi.o

calc_fp.o: \
	calc_fp.S
	../../bin/preV3_1.x calc_fp.S calc_fp.P
	../../bin/preproc.x calc_fp.P calc_fp.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_fp.o calc_fp.c
	rm -f calc_fp.c calc_fp.P
	ar rv ../lib/libsimre.a calc_fp.o

calc_froot.o: \
	calc_froot.S
	../../bin/preV3_1.x calc_froot.S calc_froot.P
	../../bin/preproc.x calc_froot.P calc_froot.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_froot.o calc_froot.c
	rm -f calc_froot.c calc_froot.P
	ar rv ../lib/libsimre.a calc_froot.o

calc_ge.o: \
	calc_ge.S
	../../bin/preV3_1.x calc_ge.S calc_ge.P
	../../bin/preproc.x calc_ge.P calc_ge.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ge.o calc_ge.c
	rm -f calc_ge.c calc_ge.P
	ar rv ../lib/libsimre.a calc_ge.o

calc_geq.o: \
	calc_geq.S
	../../bin/preV3_1.x calc_geq.S calc_geq.P
	../../bin/preproc.x calc_geq.P calc_geq.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_geq.o calc_geq.c
	rm -f calc_geq.c calc_geq.P
	ar rv ../lib/libsimre.a calc_geq.o

calc_gf.o: \
	calc_gf.S
	../../bin/preV3_1.x calc_gf.S calc_gf.P
	../../bin/preproc.x calc_gf.P calc_gf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_gf.o calc_gf.c
	rm -f calc_gf.c calc_gf.P
	ar rv ../lib/libsimre.a calc_gf.o

calc_gftopol.o: \
	calc_gftopol.S
	../../bin/preV3_1.x calc_gftopol.S calc_gftopol.P
	../../bin/preproc.x calc_gftopol.P calc_gftopol.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_gftopol.o calc_gftopol.c
	rm -f calc_gftopol.c calc_gftopol.P
	ar rv ../lib/libsimre.a calc_gftopol.o

calc_ggt.o: \
	calc_ggt.S
	../../bin/preV3_1.x calc_ggt.S calc_ggt.P
	../../bin/preproc.x calc_ggt.P calc_ggt.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ggt.o calc_ggt.c
	rm -f calc_ggt.c calc_ggt.P
	ar rv ../lib/libsimre.a calc_ggt.o

calc_herm.o: \
	calc_herm.S
	../../bin/preV3_1.x calc_herm.S calc_herm.P
	../../bin/preproc.x calc_herm.P calc_herm.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_herm.o calc_herm.c
	rm -f calc_herm.c calc_herm.P
	ar rv ../lib/libsimre.a calc_herm.o

calc_imag.o: \
	calc_imag.S
	../../bin/preV3_1.x calc_imag.S calc_imag.P
	../../bin/preproc.x calc_imag.P calc_imag.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_imag.o calc_imag.c
	rm -f calc_imag.c calc_imag.P
	ar rv ../lib/libsimre.a calc_imag.o

calc_intbas.o: \
	calc_intbas.S
	../../bin/preV3_1.x calc_intbas.S calc_intbas.P
	../../bin/preproc.x calc_intbas.P calc_intbas.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_intbas.o calc_intbas.c
	rm -f calc_intbas.c calc_intbas.P
	ar rv ../lib/libsimre.a calc_intbas.o

calc_intcoef.o: \
	calc_intcoef.S
	../../bin/preV3_1.x calc_intcoef.S calc_intcoef.P
	../../bin/preproc.x calc_intcoef.P calc_intcoef.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_intcoef.o calc_intcoef.c
	rm -f calc_intcoef.c calc_intcoef.P
	ar rv ../lib/libsimre.a calc_intcoef.o

calc_integr.o: \
	calc_integr.S
	../../bin/preV3_1.x calc_integr.S calc_integr.P
	../../bin/preproc.x calc_integr.P calc_integr.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_integr.o calc_integr.c
	rm -f calc_integr.c calc_integr.P
	ar rv ../lib/libsimre.a calc_integr.o

calc_iphi.o: \
	calc_iphi.S
	../../bin/preV3_1.x calc_iphi.S calc_iphi.P
	../../bin/preproc.x calc_iphi.P calc_iphi.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_iphi.o calc_iphi.c
	rm -f calc_iphi.c calc_iphi.P
	ar rv ../lib/libsimre.a calc_iphi.o

calc_ippcon.o: \
	calc_ippcon.S
	../../bin/preV3_1.x calc_ippcon.S calc_ippcon.P
	../../bin/preproc.x calc_ippcon.P calc_ippcon.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ippcon.o calc_ippcon.c
	rm -f calc_ippcon.c calc_ippcon.P
	ar rv ../lib/libsimre.a calc_ippcon.o

calc_irpgen.o: \
	calc_irpgen.S
	../../bin/preV3_1.x calc_irpgen.S calc_irpgen.P
	../../bin/preproc.x calc_irpgen.P calc_irpgen.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_irpgen.o calc_irpgen.c
	rm -f calc_irpgen.c calc_irpgen.P
	ar rv ../lib/libsimre.a calc_irpgen.o

calc_ispprime.o: \
	calc_ispprime.S
	../../bin/preV3_1.x calc_ispprime.S calc_ispprime.P
	../../bin/preproc.x calc_ispprime.P calc_ispprime.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ispprime.o calc_ispprime.c
	rm -f calc_ispprime.c calc_ispprime.P
	ar rv ../lib/libsimre.a calc_ispprime.o

calc_isprime.o: \
	calc_isprime.S
	../../bin/preV3_1.x calc_isprime.S calc_isprime.P
	../../bin/preproc.x calc_isprime.P calc_isprime.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_isprime.o calc_isprime.c
	rm -f calc_isprime.c calc_isprime.P
	ar rv ../lib/libsimre.a calc_isprime.o

calc_isptec.o: \
	calc_isptec.S
	../../bin/preV3_1.x calc_isptec.S calc_isptec.P
	../../bin/preproc.x calc_isptec.P calc_isptec.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_isptec.o calc_isptec.c
	rm -f calc_isptec.c calc_isptec.P
	ar rv ../lib/libsimre.a calc_isptec.o

calc_isqrt.o: \
	calc_isqrt.S
	../../bin/preV3_1.x calc_isqrt.S calc_isqrt.P
	../../bin/preproc.x calc_isqrt.P calc_isqrt.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_isqrt.o calc_isqrt.c
	rm -f calc_isqrt.c calc_isqrt.P
	ar rv ../lib/libsimre.a calc_isqrt.o

calc_jacsym.o: \
	calc_jacsym.S
	../../bin/preV3_1.x calc_jacsym.S calc_jacsym.P
	../../bin/preproc.x calc_jacsym.P calc_jacsym.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_jacsym.o calc_jacsym.c
	rm -f calc_jacsym.c calc_jacsym.P
	ar rv ../lib/libsimre.a calc_jacsym.o

calc_jinv.o: \
	calc_jinv.S
	../../bin/preV3_1.x calc_jinv.S calc_jinv.P
	../../bin/preproc.x calc_jinv.P calc_jinv.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_jinv.o calc_jinv.c
	rm -f calc_jinv.c calc_jinv.P
	ar rv ../lib/libsimre.a calc_jinv.o

calc_kgv.o: \
	calc_kgv.S
	../../bin/preV3_1.x calc_kgv.S calc_kgv.P
	../../bin/preproc.x calc_kgv.P calc_kgv.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_kgv.o calc_kgv.c
	rm -f calc_kgv.c calc_kgv.P
	ar rv ../lib/libsimre.a calc_kgv.o

calc_le.o: \
	calc_le.S
	../../bin/preV3_1.x calc_le.S calc_le.P
	../../bin/preproc.x calc_le.P calc_le.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_le.o calc_le.c
	rm -f calc_le.c calc_le.P
	ar rv ../lib/libsimre.a calc_le.o

calc_leq.o: \
	calc_leq.S
	../../bin/preV3_1.x calc_leq.S calc_leq.P
	../../bin/preproc.x calc_leq.P calc_leq.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_leq.o calc_leq.c
	rm -f calc_leq.c calc_leq.P
	ar rv ../lib/libsimre.a calc_leq.o

calc_linequ.o: \
	calc_linequ.S
	../../bin/preV3_1.x calc_linequ.S calc_linequ.P
	../../bin/preproc.x calc_linequ.P calc_linequ.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_linequ.o calc_linequ.c
	rm -f calc_linequ.c calc_linequ.P
	ar rv ../lib/libsimre.a calc_linequ.o

calc_ln.o: \
	calc_ln.S
	../../bin/preV3_1.x calc_ln.S calc_ln.P
	../../bin/preproc.x calc_ln.P calc_ln.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ln.o calc_ln.c
	rm -f calc_ln.c calc_ln.P
	ar rv ../lib/libsimre.a calc_ln.o

calc_log10.o: \
	calc_log10.S
	../../bin/preV3_1.x calc_log10.S calc_log10.P
	../../bin/preproc.x calc_log10.P calc_log10.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_log10.o calc_log10.c
	rm -f calc_log10.c calc_log10.P
	ar rv ../lib/libsimre.a calc_log10.o

calc_log2.o: \
	calc_log2.S
	../../bin/preV3_1.x calc_log2.S calc_log2.P
	../../bin/preproc.x calc_log2.P calc_log2.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_log2.o calc_log2.c
	rm -f calc_log2.c calc_log2.P
	ar rv ../lib/libsimre.a calc_log2.o

calc_m.o: \
	calc_m.S
	../../bin/preV3_1.x calc_m.S calc_m.P
	../../bin/preproc.x calc_m.P calc_m.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_m.o calc_m.c
	rm -f calc_m.c calc_m.P
	ar rv ../lib/libsimre.a calc_m.o

calc_mam2.o: \
	calc_mam2.S
	../../bin/preV3_1.x calc_mam2.S calc_mam2.P
	../../bin/preproc.x calc_mam2.P calc_mam2.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_mam2.o calc_mam2.c
	rm -f calc_mam2.c calc_mam2.P
	ar rv ../lib/libsimre.a calc_mam2.o

calc_max.o: \
	calc_max.S
	../../bin/preV3_1.x calc_max.S calc_max.P
	../../bin/preproc.x calc_max.P calc_max.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_max.o calc_max.c
	rm -f calc_max.c calc_max.P
	ar rv ../lib/libsimre.a calc_max.o

calc_mcoef.o: \
	calc_mcoef.S
	../../bin/preV3_1.x calc_mcoef.S calc_mcoef.P
	../../bin/preproc.x calc_mcoef.P calc_mcoef.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_mcoef.o calc_mcoef.c
	rm -f calc_mcoef.c calc_mcoef.P
	ar rv ../lib/libsimre.a calc_mcoef.o

calc_mex.o: \
	calc_mex.S
	../../bin/preV3_1.x calc_mex.S calc_mex.P
	../../bin/preproc.x calc_mex.P calc_mex.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_mex.o calc_mex.c
	rm -f calc_mex.c calc_mex.P
	ar rv ../lib/libsimre.a calc_mex.o

calc_min.o: \
	calc_min.S
	../../bin/preV3_1.x calc_min.S calc_min.P
	../../bin/preproc.x calc_min.P calc_min.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_min.o calc_min.c
	rm -f calc_min.c calc_min.P
	ar rv ../lib/libsimre.a calc_min.o

calc_minim.o: \
	calc_minim.S
	../../bin/preV3_1.x calc_minim.S calc_minim.P
	../../bin/preproc.x calc_minim.P calc_minim.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_minim.o calc_minim.c
	rm -f calc_minim.c calc_minim.P
	ar rv ../lib/libsimre.a calc_minim.o

calc_minor.o: \
	calc_minor.S
	../../bin/preV3_1.x calc_minor.S calc_minor.P
	../../bin/preproc.x calc_minor.P calc_minor.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_minor.o calc_minor.c
	rm -f calc_minor.c calc_minor.P
	ar rv ../lib/libsimre.a calc_minor.o

calc_mod.o: \
	calc_mod.S
	../../bin/preV3_1.x calc_mod.S calc_mod.P
	../../bin/preproc.x calc_mod.P calc_mod.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_mod.o calc_mod.c
	rm -f calc_mod.c calc_mod.P
	ar rv ../lib/libsimre.a calc_mod.o

calc_mtoi.o: \
	calc_mtoi.S
	../../bin/preV3_1.x calc_mtoi.S calc_mtoi.P
	../../bin/preproc.x calc_mtoi.P calc_mtoi.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_mtoi.o calc_mtoi.c
	rm -f calc_mtoi.c calc_mtoi.P
	ar rv ../lib/libsimre.a calc_mtoi.o

calc_mval.o: \
	calc_mval.S
	../../bin/preV3_1.x calc_mval.S calc_mval.P
	../../bin/preproc.x calc_mval.P calc_mval.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_mval.o calc_mval.c
	rm -f calc_mval.c calc_mval.P
	ar rv ../lib/libsimre.a calc_mval.o

calc_neg.o: \
	calc_neg.S
	../../bin/preV3_1.x calc_neg.S calc_neg.P
	../../bin/preproc.x calc_neg.P calc_neg.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_neg.o calc_neg.c
	rm -f calc_neg.c calc_neg.P
	ar rv ../lib/libsimre.a calc_neg.o

calc_nequ.o: \
	calc_nequ.S
	../../bin/preV3_1.x calc_nequ.S calc_nequ.P
	../../bin/preproc.x calc_nequ.P calc_nequ.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_nequ.o calc_nequ.c
	rm -f calc_nequ.c calc_nequ.P
	ar rv ../lib/libsimre.a calc_nequ.o

calc_nf.o: \
	calc_nf.S
	../../bin/preV3_1.x calc_nf.S calc_nf.P
	../../bin/preproc.x calc_nf.P calc_nf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_nf.o calc_nf.c
	rm -f calc_nf.c calc_nf.P
	ar rv ../lib/libsimre.a calc_nf.o

calc_nftopol.o: \
	calc_nftopol.S
	../../bin/preV3_1.x calc_nftopol.S calc_nftopol.P
	../../bin/preproc.x calc_nftopol.P calc_nftopol.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_nftopol.o calc_nftopol.c
	rm -f calc_nftopol.c calc_nftopol.P
	ar rv ../lib/libsimre.a calc_nftopol.o

calc_norm.o: \
	calc_norm.S
	../../bin/preV3_1.x calc_norm.S calc_norm.P
	../../bin/preproc.x calc_norm.P calc_norm.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_norm.o calc_norm.c
	rm -f calc_norm.c calc_norm.P
	ar rv ../lib/libsimre.a calc_norm.o

calc_np.o: \
	calc_np.S
	../../bin/preV3_1.x calc_np.S calc_np.P
	../../bin/preproc.x calc_np.P calc_np.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_np.o calc_np.c
	rm -f calc_np.c calc_np.P
	ar rv ../lib/libsimre.a calc_np.o

calc_npfe.o: \
	calc_npfe.S
	../../bin/preV3_1.x calc_npfe.S calc_npfe.P
	../../bin/preproc.x calc_npfe.P calc_npfe.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_npfe.o calc_npfe.c
	rm -f calc_npfe.c calc_npfe.P
	ar rv ../lib/libsimre.a calc_npfe.o

calc_nthei.o: \
	calc_nthei.S
	../../bin/preV3_1.x calc_nthei.S calc_nthei.P
	../../bin/preproc.x calc_nthei.P calc_nthei.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_nthei.o calc_nthei.c
	rm -f calc_nthei.c calc_nthei.P
	ar rv ../lib/libsimre.a calc_nthei.o

calc_ntpair.o: \
	calc_ntpair.S
	../../bin/preV3_1.x calc_ntpair.S calc_ntpair.P
	../../bin/preproc.x calc_ntpair.P calc_ntpair.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ntpair.o calc_ntpair.c
	rm -f calc_ntpair.c calc_ntpair.P
	ar rv ../lib/libsimre.a calc_ntpair.o

calc_num.o: \
	calc_num.S
	../../bin/preV3_1.x calc_num.S calc_num.P
	../../bin/preproc.x calc_num.P calc_num.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_num.o calc_num.c
	rm -f calc_num.c calc_num.P
	ar rv ../lib/libsimre.a calc_num.o

calc_or.o: \
	calc_or.S
	../../bin/preV3_1.x calc_or.S calc_or.P
	../../bin/preproc.x calc_or.P calc_or.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_or.o calc_or.c
	rm -f calc_or.c calc_or.P
	ar rv ../lib/libsimre.a calc_or.o

calc_ord.o: \
	calc_ord.S
	../../bin/preV3_1.x calc_ord.S calc_ord.P
	../../bin/preproc.x calc_ord.P calc_ord.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ord.o calc_ord.c
	rm -f calc_ord.c calc_ord.P
	ar rv ../lib/libsimre.a calc_ord.o

calc_ordtsg.o: \
	calc_ordtsg.S
	../../bin/preV3_1.x calc_ordtsg.S calc_ordtsg.P
	../../bin/preproc.x calc_ordtsg.P calc_ordtsg.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ordtsg.o calc_ordtsg.c
	rm -f calc_ordtsg.c calc_ordtsg.P
	ar rv ../lib/libsimre.a calc_ordtsg.o

calc_pconstr.o: \
	calc_pconstr.S
	../../bin/preV3_1.x calc_pconstr.S calc_pconstr.P
	../../bin/preproc.x calc_pconstr.P calc_pconstr.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_pconstr.o calc_pconstr.c
	rm -f calc_pconstr.c calc_pconstr.P
	ar rv ../lib/libsimre.a calc_pconstr.o

calc_pec.o: \
	calc_pec.S
	../../bin/preV3_1.x calc_pec.S calc_pec.P
	../../bin/preproc.x calc_pec.P calc_pec.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_pec.o calc_pec.c
	rm -f calc_pec.c calc_pec.P
	ar rv ../lib/libsimre.a calc_pec.o

calc_pfakt.o: \
	calc_pfakt.S
	../../bin/preV3_1.x calc_pfakt.S calc_pfakt.P
	../../bin/preproc.x calc_pfakt.P calc_pfakt.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_pfakt.o calc_pfakt.c
	rm -f calc_pfakt.c calc_pfakt.P
	ar rv ../lib/libsimre.a calc_pfakt.o

calc_pgen.o: \
	calc_pgen.S
	../../bin/preV3_1.x calc_pgen.S calc_pgen.P
	../../bin/preproc.x calc_pgen.P calc_pgen.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_pgen.o calc_pgen.c
	rm -f calc_pgen.c calc_pgen.P
	ar rv ../lib/libsimre.a calc_pgen.o

calc_ppcon.o: \
	calc_ppcon.S
	../../bin/preV3_1.x calc_ppcon.S calc_ppcon.P
	../../bin/preproc.x calc_ppcon.P calc_ppcon.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ppcon.o calc_ppcon.c
	rm -f calc_ppcon.c calc_ppcon.P
	ar rv ../lib/libsimre.a calc_ppcon.o

calc_prim.o: \
	calc_prim.S
	../../bin/preV3_1.x calc_prim.S calc_prim.P
	../../bin/preproc.x calc_prim.P calc_prim.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_prim.o calc_prim.c
	rm -f calc_prim.c calc_prim.P
	ar rv ../lib/libsimre.a calc_prim.o

calc_proot.o: \
	calc_proot.S
	../../bin/preV3_1.x calc_proot.S calc_proot.P
	../../bin/preproc.x calc_proot.P calc_proot.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_proot.o calc_proot.c
	rm -f calc_proot.c calc_proot.P
	ar rv ../lib/libsimre.a calc_proot.o

calc_prtoaf.o: \
	calc_prtoaf.S
	../../bin/preV3_1.x calc_prtoaf.S calc_prtoaf.P
	../../bin/preproc.x calc_prtoaf.P calc_prtoaf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_prtoaf.o calc_prtoaf.c
	rm -f calc_prtoaf.c calc_prtoaf.P
	ar rv ../lib/libsimre.a calc_prtoaf.o

calc_ptcoef.o: \
	calc_ptcoef.S
	../../bin/preV3_1.x calc_ptcoef.S calc_ptcoef.P
	../../bin/preproc.x calc_ptcoef.P calc_ptcoef.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_ptcoef.o calc_ptcoef.c
	rm -f calc_ptcoef.c calc_ptcoef.P
	ar rv ../lib/libsimre.a calc_ptcoef.o

calc_putGF2b.o: \
	calc_putGF2b.S
	../../bin/preV3_1.x calc_putGF2b.S calc_putGF2b.P
	../../bin/preproc.x calc_putGF2b.P calc_putGF2b.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_putGF2b.o calc_putGF2b.c
	rm -f calc_putGF2b.c calc_putGF2b.P
	ar rv ../lib/libsimre.a calc_putGF2b.o

calc_putb.o: \
	calc_putb.S
	../../bin/preV3_1.x calc_putb.S calc_putb.P
	../../bin/preproc.x calc_putb.P calc_putb.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_putb.o calc_putb.c
	rm -f calc_putb.c calc_putb.P
	ar rv ../lib/libsimre.a calc_putb.o

calc_putbits.o: \
	calc_putbits.S
	../../bin/preV3_1.x calc_putbits.S calc_putbits.P
	../../bin/preproc.x calc_putbits.P calc_putbits.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_putbits.o calc_putbits.c
	rm -f calc_putbits.c calc_putbits.P
	ar rv ../lib/libsimre.a calc_putbits.o

calc_puthex.o: \
	calc_puthex.S
	../../bin/preV3_1.x calc_puthex.S calc_puthex.P
	../../bin/preproc.x calc_puthex.P calc_puthex.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_puthex.o calc_puthex.c
	rm -f calc_puthex.c calc_puthex.P
	ar rv ../lib/libsimre.a calc_puthex.o

calc_puto.o: \
	calc_puto.S
	../../bin/preV3_1.x calc_puto.S calc_puto.P
	../../bin/preproc.x calc_puto.P calc_puto.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_puto.o calc_puto.c
	rm -f calc_puto.c calc_puto.P
	ar rv ../lib/libsimre.a calc_puto.o

calc_putoct.o: \
	calc_putoct.S
	../../bin/preV3_1.x calc_putoct.S calc_putoct.P
	../../bin/preproc.x calc_putoct.P calc_putoct.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_putoct.o calc_putoct.c
	rm -f calc_putoct.c calc_putoct.P
	ar rv ../lib/libsimre.a calc_putoct.o

calc_quot.o: \
	calc_quot.S
	../../bin/preV3_1.x calc_quot.S calc_quot.P
	../../bin/preproc.x calc_quot.P calc_quot.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_quot.o calc_quot.c
	rm -f calc_quot.c calc_quot.P
	ar rv ../lib/libsimre.a calc_quot.o

calc_real.o: \
	calc_real.S
	../../bin/preV3_1.x calc_real.S calc_real.P
	../../bin/preproc.x calc_real.P calc_real.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_real.o calc_real.c
	rm -f calc_real.c calc_real.P
	ar rv ../lib/libsimre.a calc_real.o

calc_red.o: \
	calc_red.S
	../../bin/preV3_1.x calc_red.S calc_red.P
	../../bin/preproc.x calc_red.P calc_red.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_red.o calc_red.c
	rm -f calc_red.c calc_red.P
	ar rv ../lib/libsimre.a calc_red.o

calc_reg.o: \
	calc_reg.S
	../../bin/preV3_1.x calc_reg.S calc_reg.P
	../../bin/preproc.x calc_reg.P calc_reg.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_reg.o calc_reg.c
	rm -f calc_reg.c calc_reg.P
	ar rv ../lib/libsimre.a calc_reg.o

calc_relcln.o: \
	calc_relcln.S
	../../bin/preV3_1.x calc_relcln.S calc_relcln.P
	../../bin/preproc.x calc_relcln.P calc_relcln.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_relcln.o calc_relcln.c
	rm -f calc_relcln.c calc_relcln.P
	ar rv ../lib/libsimre.a calc_relcln.o

calc_resul.o: \
	calc_resul.S
	../../bin/preV3_1.x calc_resul.S calc_resul.P
	../../bin/preproc.x calc_resul.P calc_resul.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_resul.o calc_resul.c
	rm -f calc_resul.c calc_resul.P
	ar rv ../lib/libsimre.a calc_resul.o

calc_rk.o: \
	calc_rk.S
	../../bin/preV3_1.x calc_rk.S calc_rk.P
	../../bin/preproc.x calc_rk.P calc_rk.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_rk.o calc_rk.c
	rm -f calc_rk.c calc_rk.P
	ar rv ../lib/libsimre.a calc_rk.o

calc_rk2d.o: \
	calc_rk2d.S
	../../bin/preV3_1.x calc_rk2d.S calc_rk2d.P
	../../bin/preproc.x calc_rk2d.P calc_rk2d.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_rk2d.o calc_rk2d.c
	rm -f calc_rk2d.c calc_rk2d.P
	ar rv ../lib/libsimre.a calc_rk2d.o

calc_rkbsd.o: \
	calc_rkbsd.S
	../../bin/preV3_1.x calc_rkbsd.S calc_rkbsd.P
	../../bin/preproc.x calc_rkbsd.P calc_rkbsd.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_rkbsd.o calc_rkbsd.c
	rm -f calc_rkbsd.c calc_rkbsd.P
	ar rv ../lib/libsimre.a calc_rkbsd.o

calc_rkg2d.o: \
	calc_rkg2d.S
	../../bin/preV3_1.x calc_rkg2d.S calc_rkg2d.P
	../../bin/preproc.x calc_rkg2d.P calc_rkg2d.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_rkg2d.o calc_rkg2d.c
	rm -f calc_rkg2d.c calc_rkg2d.P
	ar rv ../lib/libsimre.a calc_rkg2d.o

calc_root.o: \
	calc_root.S
	../../bin/preV3_1.x calc_root.S calc_root.P
	../../bin/preproc.x calc_root.P calc_root.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_root.o calc_root.c
	rm -f calc_root.c calc_root.P
	ar rv ../lib/libsimre.a calc_root.o

calc_rper.o: \
	calc_rper.S
	../../bin/preV3_1.x calc_rper.S calc_rper.P
	../../bin/preproc.x calc_rper.P calc_rper.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_rper.o calc_rper.c
	rm -f calc_rper.c calc_rper.P
	ar rv ../lib/libsimre.a calc_rper.o

calc_sfp.o: \
	calc_sfp.S
	../../bin/preV3_1.x calc_sfp.S calc_sfp.P
	../../bin/preproc.x calc_sfp.P calc_sfp.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_sfp.o calc_sfp.c
	rm -f calc_sfp.c calc_sfp.P
	ar rv ../lib/libsimre.a calc_sfp.o

calc_sgn.o: \
	calc_sgn.S
	../../bin/preV3_1.x calc_sgn.S calc_sgn.P
	../../bin/preproc.x calc_sgn.P calc_sgn.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_sgn.o calc_sgn.c
	rm -f calc_sgn.c calc_sgn.P
	ar rv ../lib/libsimre.a calc_sgn.o

calc_sgnfeq.o: \
	calc_sgnfeq.S
	../../bin/preV3_1.x calc_sgnfeq.S calc_sgnfeq.P
	../../bin/preproc.x calc_sgnfeq.P calc_sgnfeq.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_sgnfeq.o calc_sgnfeq.c
	rm -f calc_sgnfeq.c calc_sgnfeq.P
	ar rv ../lib/libsimre.a calc_sgnfeq.o

calc_skalar.o: \
	calc_skalar.S
	../../bin/preV3_1.x calc_skalar.S calc_skalar.P
	../../bin/preproc.x calc_skalar.P calc_skalar.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_skalar.o calc_skalar.c
	rm -f calc_skalar.c calc_skalar.P
	ar rv ../lib/libsimre.a calc_skalar.o

calc_sort.o: \
	calc_sort.S
	../../bin/preV3_1.x calc_sort.S calc_sort.P
	../../bin/preproc.x calc_sort.P calc_sort.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_sort.o calc_sort.c
	rm -f calc_sort.c calc_sort.P
	ar rv ../lib/libsimre.a calc_sort.o

calc_sqrt.o: \
	calc_sqrt.S
	../../bin/preV3_1.x calc_sqrt.S calc_sqrt.P
	../../bin/preproc.x calc_sqrt.P calc_sqrt.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_sqrt.o calc_sqrt.c
	rm -f calc_sqrt.c calc_sqrt.P
	ar rv ../lib/libsimre.a calc_sqrt.o

calc_stfkt.o: \
	calc_stfkt.S
	../../bin/preV3_1.x calc_stfkt.S calc_stfkt.P
	../../bin/preproc.x calc_stfkt.P calc_stfkt.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_stfkt.o calc_stfkt.c
	rm -f calc_stfkt.c calc_stfkt.P
	ar rv ../lib/libsimre.a calc_stfkt.o

calc_sum.o: \
	calc_sum.S
	../../bin/preV3_1.x calc_sum.S calc_sum.P
	../../bin/preproc.x calc_sum.P calc_sum.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_sum.o calc_sum.c
	rm -f calc_sum.c calc_sum.P
	ar rv ../lib/libsimre.a calc_sum.o

calc_swnf.o: \
	calc_swnf.S
	../../bin/preV3_1.x calc_swnf.S calc_swnf.P
	../../bin/preproc.x calc_swnf.P calc_swnf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_swnf.o calc_swnf.c
	rm -f calc_swnf.c calc_swnf.P
	ar rv ../lib/libsimre.a calc_swnf.o

calc_taalg.o: \
	calc_taalg.S
	../../bin/preV3_1.x calc_taalg.S calc_taalg.P
	../../bin/preproc.x calc_taalg.P calc_taalg.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_taalg.o calc_taalg.c
	rm -f calc_taalg.c calc_taalg.P
	ar rv ../lib/libsimre.a calc_taalg.o

calc_tav.o: \
	calc_tav.S
	../../bin/preV3_1.x calc_tav.S calc_tav.P
	../../bin/preproc.x calc_tav.P calc_tav.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_tav.o calc_tav.c
	rm -f calc_tav.c calc_tav.P
	ar rv ../lib/libsimre.a calc_tav.o

calc_tofl.o: \
	calc_tofl.S
	../../bin/preV3_1.x calc_tofl.S calc_tofl.P
	../../bin/preproc.x calc_tofl.P calc_tofl.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_tofl.o calc_tofl.c
	rm -f calc_tofl.c calc_tofl.P
	ar rv ../lib/libsimre.a calc_tofl.o

calc_tors.o: \
	calc_tors.S
	../../bin/preV3_1.x calc_tors.S calc_tors.P
	../../bin/preproc.x calc_tors.P calc_tors.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_tors.o calc_tors.c
	rm -f calc_tors.c calc_tors.P
	ar rv ../lib/libsimre.a calc_tors.o

calc_trace.o: \
	calc_trace.S
	../../bin/preV3_1.x calc_trace.S calc_trace.P
	../../bin/preproc.x calc_trace.P calc_trace.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_trace.o calc_trace.c
	rm -f calc_trace.c calc_trace.P
	ar rv ../lib/libsimre.a calc_trace.o

calc_transp.o: \
	calc_transp.S
	../../bin/preV3_1.x calc_transp.S calc_transp.P
	../../bin/preproc.x calc_transp.P calc_transp.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_transp.o calc_transp.c
	rm -f calc_transp.c calc_transp.P
	ar rv ../lib/libsimre.a calc_transp.o

calc_trig.o: \
	calc_trig.S
	../../bin/preV3_1.x calc_trig.S calc_trig.P
	../../bin/preproc.x calc_trig.P calc_trig.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_trig.o calc_trig.c
	rm -f calc_trig.c calc_trig.P
	ar rv ../lib/libsimre.a calc_trig.o

calc_unit.o: \
	calc_unit.S
	../../bin/preV3_1.x calc_unit.S calc_unit.P
	../../bin/preproc.x calc_unit.P calc_unit.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_unit.o calc_unit.c
	rm -f calc_unit.c calc_unit.P
	ar rv ../lib/libsimre.a calc_unit.o

calc_vcoef.o: \
	calc_vcoef.S
	../../bin/preV3_1.x calc_vcoef.S calc_vcoef.P
	../../bin/preproc.x calc_vcoef.P calc_vcoef.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_vcoef.o calc_vcoef.c
	rm -f calc_vcoef.c calc_vcoef.P
	ar rv ../lib/libsimre.a calc_vcoef.o

calc_whei.o: \
	calc_whei.S
	../../bin/preV3_1.x calc_whei.S calc_whei.P
	../../bin/preproc.x calc_whei.P calc_whei.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_whei.o calc_whei.c
	rm -f calc_whei.c calc_whei.P
	ar rv ../lib/libsimre.a calc_whei.o

calc_zmcon.o: \
	calc_zmcon.S
	../../bin/preV3_1.x calc_zmcon.S calc_zmcon.P
	../../bin/preproc.x calc_zmcon.P calc_zmcon.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_zmcon.o calc_zmcon.c
	rm -f calc_zmcon.c calc_zmcon.P
	ar rv ../lib/libsimre.a calc_zmcon.o

calc_zvcon.o: \
	calc_zvcon.S
	../../bin/preV3_1.x calc_zvcon.S calc_zvcon.P
	../../bin/preproc.x calc_zvcon.P calc_zvcon.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o calc_zvcon.o calc_zvcon.c
	rm -f calc_zvcon.c calc_zvcon.P
	ar rv ../lib/libsimre.a calc_zvcon.o

carrqnf1.o: \
	carrqnf1.S
	../../bin/preV3_1.x carrqnf1.S carrqnf1.P
	../../bin/preproc.x carrqnf1.P carrqnf1.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o carrqnf1.o carrqnf1.c
	rm -f carrqnf1.c carrqnf1.P
	ar rv ../lib/libsimre.a carrqnf1.o

casi_ecgnp.o: \
	casi_ecgnp.S
	../../bin/preV3_1.x casi_ecgnp.S casi_ecgnp.P
	../../bin/preproc.x casi_ecgnp.P casi_ecgnp.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o casi_ecgnp.o casi_ecgnp.c
	rm -f casi_ecgnp.c casi_ecgnp.P
	ar rv ../lib/libsimre.a casi_ecgnp.o

casi_ecnpscf.o: \
	casi_ecnpscf.S
	../../bin/preV3_1.x casi_ecnpscf.S casi_ecnpscf.P
	../../bin/preproc.x casi_ecnpscf.P casi_ecnpscf.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o casi_ecnpscf.o casi_ecnpscf.c
	rm -f casi_ecnpscf.c casi_ecnpscf.P
	ar rv ../lib/libsimre.a casi_ecnpscf.o

casi_f1root.o: \
	casi_f1root.S
	../../bin/preV3_1.x casi_f1root.S casi_f1root.P
	../../bin/preproc.x casi_f1root.P casi_f1root.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o casi_f1root.o casi_f1root.c
	rm -f casi_f1root.c casi_f1root.P
	ar rv ../lib/libsimre.a casi_f1root.o

casi_irpgen.o: \
	casi_irpgen.S
	../../bin/preV3_1.x casi_irpgen.S casi_irpgen.P
	../../bin/preproc.x casi_irpgen.P casi_irpgen.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o casi_irpgen.o casi_irpgen.c
	rm -f casi_irpgen.c casi_irpgen.P
	ar rv ../lib/libsimre.a casi_irpgen.o

casi_np.o: \
	casi_np.S
	../../bin/preV3_1.x casi_np.S casi_np.P
	../../bin/preproc.x casi_np.P casi_np.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o casi_np.o casi_np.c
	rm -f casi_np.c casi_np.P
	ar rv ../lib/libsimre.a casi_np.o

ecgf2npcasv.o: \
	ecgf2npcasv.S
	../../bin/preV3_1.x ecgf2npcasv.S ecgf2npcasv.P
	../../bin/preproc.x ecgf2npcasv.P ecgf2npcasv.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o ecgf2npcasv.o ecgf2npcasv.c
	rm -f ecgf2npcasv.c ecgf2npcasv.P
	ar rv ../lib/libsimre.a ecgf2npcasv.o

ecrbtco_old.o: \
	ecrbtco_old.S
	../../bin/preV3_1.x ecrbtco_old.S ecrbtco_old.P
	../../bin/preproc.x ecrbtco_old.P ecrbtco_old.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o ecrbtco_old.o ecrbtco_old.c
	rm -f ecrbtco_old.c ecrbtco_old.P
	ar rv ../lib/libsimre.a ecrbtco_old.o

ecrsnftoic_o.o: \
	ecrsnftoic_o.S
	../../bin/preV3_1.x ecrsnftoic_o.S ecrsnftoic_o.P
	../../bin/preproc.x ecrsnftoic_o.P ecrsnftoic_o.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o ecrsnftoic_o.o ecrsnftoic_o.c
	rm -f ecrsnftoic_o.c ecrsnftoic_o.P
	ar rv ../lib/libsimre.a ecrsnftoic_o.o

ecrtoic_o.o: \
	ecrtoic_o.S
	../../bin/preV3_1.x ecrtoic_o.S ecrtoic_o.P
	../../bin/preproc.x ecrtoic_o.P ecrtoic_o.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o ecrtoic_o.o ecrtoic_o.c
	rm -f ecrtoic_o.c ecrtoic_o.P
	ar rv ../lib/libsimre.a ecrtoic_o.o

eval.o: \
	eval.S
	../../bin/preV3_1.x eval.S eval.P
	../../bin/preproc.x eval.P eval.c
	$(CC) $(CFLAGS_SIMCALC) $(CPPFLAGS_SIMCALC) -c -o eval.o eval.c
	rm -f eval.c eval.P
	ar rv ../lib/libsimre.a eval.o

ranlib:
	- ranlib ../lib/libsimre.a
