#define compute_ggt Ecompute_ggt
#define add  Eadd
#define incr Eincr
#define sub  Esub    
#define decr Edecr
#define mult Emult    
/* Sonderbehandlung, da quad in sys/types.h als Typ deklariert */
/* Don't define quad Equad                                     */
#define shift Eshift
#define div  Ediv
#define expo Eexpo
#define wurzel Ewurzel
#define n_wurzel En_wurzel
#define lb Elb
#define quersumme Equersumme
#define alt_quersumme Ealt_quersumme
#define jacobi Ejacobi
#define comp   Ecomp      
#define trans Etrans  
#define zuweis Ezuweis
#define zuweis_int Ezuweis_int
#define even Eeven              
#define mod4 Emod4
#define mod8 Emod8      
#define zufall Ezufall
#define madd Emadd
#define msub Emsub
#define mmult Emmult
#define mquad Emquad
#define mdiv Emdiv
#define mexp Emexp
#define GGT EGGT
#define readue Ereadue   
#define vreadue Evreadue
#define readuefile Ereaduefile
#define writeue Ewriteue
#define vwriteue Evwriteue
#define writeuefile Ewriteuefile
#define readx Eread   
#define readxfile Ereadfile
#define read_long Eread_long
#define writex Ewritex
#define vwritex Evwritex
#define write_long Ewrite_long
#define readb Ereadb
#define writeb Ewriteb
#define overflow Eoverflow
