/*M
.SH NAME
getmagf2 - get matrix of Galois-field with characteristic 2 elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

matrix getmagf2(G, VL)
obj G;
list VL; 

.SH DESCRIPTION
getmagf2() is equivalent to fgetmagf2() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetmagf2
M*/


/*H
	Version 1	22.06.1995	E.Herrmann
   DATE getmagf2      : 951201
H*/
/*
	For the definition of getmagf2 please refer to the header file _matr2.h
*/ 
