/*M
.SH NAME
getmagfs - get matrix of Galois-field with single characteristic elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

matrix getmagfs(p, AL, V)
single p;
list AL,V;

.SH DESCRIPTION
getmagfs() is equivalent to fgetmagfs() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetmagfs
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getmagfs      : 910915.941201
H*/
/*
	For the definition of getmagfs please refer to the header file _matr2.h.
*/
