/*M
.SH NAME
getvecgfs - get vector of Galois-field with single characteristic elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

vec getvecgfs(p, AL, VL)
single p;
list AL,VL;

.SH DESCRIPTION
getvecgfs() is equivalent to fgetvecgfs() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecgfs
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecgfs     : 910915.941201
H*/
/*
	For the definition of getvecgfs please refer to the header file _matr2.h.
*/
