/*M
.SH NAME
getvecnfs - get vector of number field elements, sparse representation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

vec getvecnfs(F, VL)
pol F;
list VL;

.SH DESCRIPTION
getvecnfs() is equivalent to fgetvecnfs() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecnfs
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecnfs     : 910915.941201
H*/
/*
	For the definition of getvecnfs please refer to the header file _matr2.h.
*/
