/*M
.SH NAME
getvecgf2 - get vector of Galois-field of characteristic 2 elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

vec getvecgf2(G, VL)
obj G;
list VL; 

.SH DESCRIPTION
getvecgf2() is equivalent to fgetvecgf2() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecgf2
M*/


/*H
	Version 1	22.06.1995	E.Herrmann
   DATE getvecgf2     : 951201
H*/
/*
	For the definition of getvecgf2 please refer to the header file _matr2.h
*/ 
