/*M
.SH NAME
getvecnf - get vector of number field elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

vec getvecnf(F, VL)
pol F;
list VL;

.SH DESCRIPTION
getvecnf() is equivalent to fgetvecnf() reading from standard input, i.e. using stdin as input file pf.

.SH SEE ALSO
fgetvecnf
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE getvecnf      : 910915.941201
H*/
/*
	For the definition of getvecnf please refer to the header file _matr2.h.
*/
