/*M
.SH NAME
putmagfs - put matrix of Galois-field with single characteristic elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

single putmagfs(p, AL, M, V)
single p;
list AL,V;
matrix M;

.SH DESCRIPTION
putmagfs() is equivalent to fputmagfs() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmagfs
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmagfs      : 910915.941201
H*/
/*
	For the definition of putmagfs please refer to the header file _matr2.h.
*/
