/*M
.SH NAME
putmanfs - put matrix of number field elements, sparse representation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

single putmanfs(F, M, VL)
pol F;
matrix M;
list VL;

.SH DESCRIPTION
putmanfs() is equivalent to fputmanfs() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputmanfs
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putmanfs      : 910915.941201
H*/
/*
	For the definition of putmanfs please refer to the header file _matr2.h.
*/
