/*M
.SH NAME
putvecnfs - put vector of number field elements, sparse representation (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

single putvecnfs(F, V, VL)
pol F;
vec V;
list VL;

.SH DESCRIPTION
putvecnfs() is equivalent to fputvecnfs() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecnfs
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecnfs     : 910915.941201
H*/
/*
	For the definition of putvecnfs please refer to the header file _matr2.h.
*/
