/*M
.SH NAME
putvecgfs - put vector of Galois-field with single characteristic elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

single putvecgfs(p, AL, V, VL)
single p;
list AL,VL;
vec V;

.SH DESCRIPTION
putvecgfs() is equivalent to fputvecgfs() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecgfs
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecgfs     : 910915.941201
H*/
/*
	For the definition of putvecgfs please refer to the header file _matr2.h.
*/
