/*M
.SH NAME
putvecnf - put vector of number field elements (MACRO)

.SH SYNOPSIS
.nf
#include<_matr2.h>

single putvecnf(F, V, VL)
pol F;
vec V;
list VL;

.SH DESCRIPTION
putvecnf() is equivalent to fputvecnf() writing to standard output, i.e. using stdout as output file pf.

.SH SEE ALSO
fputvecnf
M*/


/*H
	Version 1       17.03.1990      Th. Weis
	Version 2	18.11.94	Macro nur noch im Header definiert. MP
   DATE putvecnf      : 910915.941201
H*/
/*
	For the definition of putvecnf please refer to the header file _matr2.h.
*/
